import Mathlib
import «M2rGroup7».Lemmas.SylowUtils
import «M2rGroup7».Lemmas.LinearAlgebraUtils
import «M2rGroup7».Lemmas.GroupTheoryLemmas
import «M2rGroup7».Lemmas.ClassificationUtils
import «M2rGroup7».Lemmas.HomomorphismUtils
import «M2rGroup7».Lemmas.NumberTheoryUtils
import «M2rGroup7».P2qClassification.CycPGroupClassification

/-- Canonical nontrivial action `C_2 →* Aut(C_{p^2})`, image of order 2. -/
def canonicalC2OnCp2Action {p : ℕ} [h_p_prime : Fact p.Prime] (h_p_ne_2 : p ≠ 2) :
    CyclicGroup 2 →* MulAut (CyclicGroup (p ^ 2)) :=
  haveI := h_p_prime
  haveI : Fact (Nat.Prime 2) := ⟨by norm_num⟩
  haveI : NeZero (p ^ 2) := ⟨pow_ne_zero 2 h_p_prime.out.ne_zero⟩
  haveI : NeZero (2 : ℕ) := ⟨by norm_num⟩
  haveI : NeZero ((2:ℕ) ^ 1) := ⟨pow_ne_zero 1 (by norm_num)⟩
  transportCpCqHom (pow_one 2) (rfl : p ^ 2 = p ^ 2)
    (canonicalAction 2 p 2 1 (Ne.symm h_p_ne_2) h_p_ne_2 (by norm_num)
       1 (by
          have h := (Nat.le_min.mp (one_le_min_two_factorization_two h_p_ne_2)).2
          exact Nat.le_min.mpr ⟨le_refl 1, h⟩))

/-! ## Canonical actions on `C_p × C_p` for the `C_2` factor.

We build two elementary automorphisms of `C_p × C_p`: inversion on the second
coordinate (`cpcpInvSecond`) and inversion on both coordinates (`cpcpInvBoth`).
Both have order dividing 2; we turn them into actions `C_2 →* MulAut (C_p × C_p)`
via `cyclicHom`. -/

/-- Inversion on the second coordinate of `C_p × C_p`. -/
def cpcpInvSecond (p : ℕ) [NeZero p] : MulAut (CyclicGroup p × CyclicGroup p) where
  toFun x := (x.1, x.2⁻¹)
  invFun x := (x.1, x.2⁻¹)
  left_inv := by rintro ⟨a, b⟩; simp
  right_inv := by rintro ⟨a, b⟩; simp
  map_mul' := by
    rintro ⟨a₁, b₁⟩ ⟨a₂, b₂⟩
    refine Prod.ext rfl ?_
    change (b₁ * b₂)⁻¹ = b₁⁻¹ * b₂⁻¹
    rw [mul_inv]

/-- Inversion on both coordinates of `C_p × C_p`. -/
def cpcpInvBoth (p : ℕ) [NeZero p] : MulAut (CyclicGroup p × CyclicGroup p) where
  toFun x := (x.1⁻¹, x.2⁻¹)
  invFun x := (x.1⁻¹, x.2⁻¹)
  left_inv := by rintro ⟨a, b⟩; simp
  right_inv := by rintro ⟨a, b⟩; simp
  map_mul' := by
    rintro ⟨a₁, b₁⟩ ⟨a₂, b₂⟩
    refine Prod.ext ?_ ?_
    · change (a₁ * a₂)⁻¹ = a₁⁻¹ * a₂⁻¹; rw [mul_inv]
    · change (b₁ * b₂)⁻¹ = b₁⁻¹ * b₂⁻¹; rw [mul_inv]

lemma cpcpInvSecond_sq (p : ℕ) [NeZero p] : (cpcpInvSecond p) ^ 2 = 1 := by
  ext x
  · rw [sq, MulAut.mul_apply, MulAut.one_apply]
    change ((x.1, x.2⁻¹).1, (x.1, x.2⁻¹).2⁻¹).1 = x.1
    simp
  · rw [sq, MulAut.mul_apply, MulAut.one_apply]
    change ((x.1, x.2⁻¹).1, (x.1, x.2⁻¹).2⁻¹).2 = x.2
    simp

lemma cpcpInvBoth_sq (p : ℕ) [NeZero p] : (cpcpInvBoth p) ^ 2 = 1 := by
  ext x
  · rw [sq, MulAut.mul_apply, MulAut.one_apply]
    change ((x.1⁻¹, x.2⁻¹).1⁻¹, (x.1⁻¹, x.2⁻¹).2⁻¹).1 = x.1
    simp
  · rw [sq, MulAut.mul_apply, MulAut.one_apply]
    change ((x.1⁻¹, x.2⁻¹).1⁻¹, (x.1⁻¹, x.2⁻¹).2⁻¹).2 = x.2
    simp

/-- Canonical action `C_2 →* Aut(C_p × C_p)` with image generated by inversion on the
second coordinate. -/
def canonicalC2OnCpCpAction_r1 (p : ℕ) [NeZero p] :
    CyclicGroup 2 →* MulAut (CyclicGroup p × CyclicGroup p) :=
  cyclicHom 2 (cpcpInvSecond p) (cpcpInvSecond_sq p)

/-- Canonical action `C_2 →* Aut(C_p × C_p)` with image generated by inversion on both
coordinates (the "minus identity" action). -/
def canonicalC2OnCpCpAction_r2 (p : ℕ) [NeZero p] :
    CyclicGroup 2 →* MulAut (CyclicGroup p × CyclicGroup p) :=
  cyclicHom 2 (cpcpInvBoth p) (cpcpInvBoth_sq p)

/-! ## Conjugacy classification of order-two elements of `MulAut(C_p × C_p)`.

For `p` an odd prime, every order-two element of `MulAut(C_p × C_p)` is conjugate
in `MulAut(C_p × C_p)` to either `cpcpInvSecond p` or `cpcpInvBoth p`. -/

/-- For an odd prime `p`, every order-two element `σ` of `MulAut(C_p × C_p)` is
conjugate to one of the two canonical inversion automorphisms `cpcpInvSecond p` or
`cpcpInvBoth p`.

The proof strategy is to view `Additive (C_p × C_p)` as a 2-dimensional `F_p`-vector
space and analyse the ±1 eigenspaces of the linear automorphism corresponding to `σ`.
Either both `+1` and `-1` eigenspaces are 1-dimensional (giving the `cpcpInvSecond`
case via a change-of-basis), or `σ` acts as `-id` (giving the `cpcpInvBoth` case
directly). -/
lemma mulAut_cpcp_order_two_conj {p : ℕ} [hp : Fact p.Prime] (hp_ne_2 : p ≠ 2)
    (σ : MulAut (CyclicGroup p × CyclicGroup p)) (hσ : orderOf σ = 2) :
    IsConj (cpcpInvSecond p) σ ∨ IsConj (cpcpInvBoth p) σ := by
  set H := CyclicGroup p × CyclicGroup p with hH_def
  haveI : NeZero p := ⟨hp.out.pos.ne'⟩
  -- σ² = 1, σ ≠ 1
  have hσ_sq : σ ^ 2 = 1 := by
    have h := pow_orderOf_eq_one σ; rw [hσ] at h; exact h
  have hσ_ne_one : σ ≠ 1 := by
    intro h; rw [h, orderOf_one] at hσ; exact absurd hσ (by norm_num)
  -- σ ∘ σ = id pointwise
  have hσσ : ∀ x : H, σ (σ x) = x := by
    intro x
    have h : (σ * σ) x = (1 : MulAut H) x := by
      rw [show σ * σ = σ ^ 2 from (sq σ).symm, hσ_sq]
    rwa [MulAut.mul_apply, MulAut.one_apply] at h
  -- p-power triviality
  have h_pow_p : ∀ h : H, h ^ p = 1 := by
    intro h
    obtain ⟨a, b⟩ := h
    have h_card_cp : Nat.card (CyclicGroup p) = p := card_cyclicGroup p
    have h_one : ∀ z : CyclicGroup p, z ^ p = 1 := fun z => by
      have h := pow_card_eq_one' (G := CyclicGroup p) (x := z)
      rwa [h_card_cp] at h
    change (a ^ p, b ^ p) = (1, 1)
    rw [h_one a, h_one b]
  -- Additive structure
  have h_nsmul_p : ∀ x : Additive H, (p : ℕ) • x = 0 := by
    intro x
    have : Additive.ofMul (Additive.toMul x ^ p) = (p : ℕ) • x := ofMul_pow p (Additive.toMul x)
    rw [← this]
    change Additive.ofMul _ = Additive.ofMul 1
    rw [h_pow_p]
  haveI inst_mod : Module (ZMod p) (Additive H) := AddCommGroup.zmodModule h_nsmul_p
  haveI : Fintype H := instFintypeProd _ _
  haveI : Fintype (ZMod p) := ZMod.fintype p
  haveI : Fintype (Additive H) := Additive.fintype
  have h_card_addH : Nat.card (Additive H) = p ^ 2 := by
    rw [show Nat.card (Additive H) = Nat.card H from Nat.card_congr Additive.toMul]
    change Nat.card (CyclicGroup p × CyclicGroup p) = p ^ 2
    rw [Nat.card_prod, card_cyclicGroup]; ring
  have h_card_zmod : Nat.card (ZMod p) = p := by
    rw [Nat.card_eq_fintype_card, ZMod.card]
  have h_finrank_addH : Module.finrank (ZMod p) (Additive H) = 2 := by
    have h := Module.card_eq_pow_finrank (K := ZMod p) (V := Additive H)
    rw [← Nat.card_eq_fintype_card, ← Nat.card_eq_fintype_card,
        h_card_addH, h_card_zmod] at h
    have hp2 : 2 ≤ p := hp.out.two_le
    exact (Nat.pow_right_injective hp2 h).symm
  -- Case A: σ = cpcpInvBoth p
  by_cases h_eq_both : σ = cpcpInvBoth p
  · right
    rw [← h_eq_both]
  -- Case B: σ ≠ cpcpInvBoth p
  · left
    -- Step 1: find z with σ z ≠ z⁻¹ (otherwise σ = cpcpInvBoth p)
    have h_exists_z : ∃ z : H, σ z ≠ z⁻¹ := by
      by_contra h_all
      push_neg at h_all
      apply h_eq_both
      ext x
      · show (σ x).1 = (cpcpInvBoth p x).1
        have h := h_all x
        change (σ x).1 = x.1⁻¹
        have h_inv : σ x = x⁻¹ := h
        rw [h_inv]
        rfl
      · show (σ x).2 = (cpcpInvBoth p x).2
        have h := h_all x
        change (σ x).2 = x.2⁻¹
        have h_inv : σ x = x⁻¹ := h
        rw [h_inv]
        rfl
    obtain ⟨z, hz⟩ := h_exists_z
    -- u := z * σ z is a +1 eigenvector
    set u : H := z * σ z with hu_def
    have hu_ne : u ≠ 1 := by
      intro h
      apply hz
      have h_eq : z * σ z = 1 := h
      exact mul_eq_one_iff_eq_inv'.mp h_eq
    have hu_fixed : σ u = u := by
      show σ (z * σ z) = z * σ z
      rw [map_mul, hσσ z]
      rw [mul_comm]
    -- Step 2: find w with σ w ≠ w (otherwise σ = 1)
    have h_exists_w : ∃ w : H, σ w ≠ w := by
      by_contra h_all
      push_neg at h_all
      apply hσ_ne_one
      ext x
      · show (σ x).1 = ((1 : MulAut H) x).1
        rw [h_all x]; rfl
      · show (σ x).2 = ((1 : MulAut H) x).2
        rw [h_all x]; rfl
    obtain ⟨w, hw⟩ := h_exists_w
    -- v := w * (σ w)⁻¹ is a -1 eigenvector
    set v : H := w * (σ w)⁻¹ with hv_def
    have hv_ne : v ≠ 1 := by
      intro h
      apply hw
      have h_eq : w * (σ w)⁻¹ = 1 := h
      have := mul_inv_eq_one.mp h_eq
      exact this.symm
    have hv_inv : σ v = v⁻¹ := by
      show σ (w * (σ w)⁻¹) = (w * (σ w)⁻¹)⁻¹
      rw [map_mul, map_inv, hσσ w, mul_inv_rev, inv_inv, mul_comm]
    -- Step 3: u_add, v_add are linearly independent eigenvectors
    set u_add : Additive H := Additive.ofMul u with hu_add_def
    set v_add : Additive H := Additive.ofMul v with hv_add_def
    have hu_add_ne : u_add ≠ 0 := by
      intro h
      apply hu_ne
      change Additive.toMul u_add = Additive.toMul (0 : Additive H)
      rw [h]
    have hv_add_ne : v_add ≠ 0 := by
      intro h
      apply hv_ne
      change Additive.toMul v_add = Additive.toMul (0 : Additive H)
      rw [h]
    -- Build ψ from σ via AddAutAdditive.symm
    let ψ : Additive H ≃+ Additive H := (AddAutAdditive (G := H)).symm σ
    -- ψ u_add = u_add (eigenvalue 1)
    have h_ψ_u : ψ u_add = u_add := by
      show Additive.ofMul (σ u) = Additive.ofMul u
      rw [hu_fixed]
    -- ψ v_add = -v_add (eigenvalue -1)
    have h_ψ_v : ψ v_add = -v_add := by
      show Additive.ofMul (σ v) = -Additive.ofMul v
      rw [hv_inv]
      rfl
    -- ψ is ZMod p-linear
    have h_ψ_smul : ∀ (r : ZMod p) (x : Additive H), ψ (r • x) = r • ψ x := by
      intro r x
      exact (AddMonoidHom.toZModLinearMap p ψ.toAddMonoidHom).map_smul r x
    -- Linear independence of {u_add, v_add}: a * u_add + b * v_add = 0 ⇒ a = b = 0
    have h_lin_indep :
        ∀ (a b : ZMod p), a • u_add + b • v_add = 0 → a = 0 ∧ b = 0 := by
      intro a b h_lc
      -- Apply ψ to both sides: a • u_add - b • v_add = 0
      have h_ψ_lc : ψ (a • u_add + b • v_add) = 0 := by rw [h_lc, map_zero]
      rw [map_add, h_ψ_smul, h_ψ_smul, h_ψ_u, h_ψ_v, smul_neg] at h_ψ_lc
      -- h_ψ_lc : a • u_add + -(b • v_add) = 0
      -- Combined with original: add them to get 2a • u_add = 0
      have h_sum : (2 * a) • u_add = 0 := by
        have h_add : (a • u_add + b • v_add) + (a • u_add + -(b • v_add)) = 0 := by
          rw [h_lc, h_ψ_lc, add_zero]
        have : (a • u_add + b • v_add) + (a • u_add + -(b • v_add)) =
            (a + a) • u_add := by
          rw [show a • u_add + b • v_add + (a • u_add + -(b • v_add)) =
            (a • u_add + a • u_add) + (b • v_add + -(b • v_add)) by abel,
            add_neg_cancel, add_zero, ← add_smul]
        rw [this] at h_add
        rw [show (2 * a) = a + a by ring]
        exact h_add
      -- subtract: 2b • v_add = 0
      have h_sub : (2 * b) • v_add = 0 := by
        have h_sub_eq : (a • u_add + b • v_add) - (a • u_add + -(b • v_add)) = 0 := by
          rw [h_lc, h_ψ_lc, sub_zero]
        have : (a • u_add + b • v_add) - (a • u_add + -(b • v_add)) =
            (b + b) • v_add := by
          rw [show a • u_add + b • v_add - (a • u_add + -(b • v_add)) =
            (a • u_add - a • u_add) + (b • v_add - -(b • v_add)) by abel,
            sub_self, zero_add, sub_neg_eq_add, ← add_smul]
        rw [this] at h_sub_eq
        rw [show (2 * b) = b + b by ring]
        exact h_sub_eq
      -- 2 is invertible in ZMod p (since p ≠ 2)
      have h2_ne_zero : (2 : ZMod p) ≠ 0 := by
        intro h2
        have hcast : ((2 : ℕ) : ZMod p) = 0 := by exact_mod_cast h2
        have h_dvd : p ∣ 2 := (ZMod.natCast_eq_zero_iff 2 p).mp hcast
        have h_p_eq : p = 2 :=
          (Nat.prime_dvd_prime_iff_eq hp.out Nat.prime_two).mp h_dvd
        exact hp_ne_2 h_p_eq
      have ha : a = 0 := by
        have h2a : (2 * a) = 0 := by
          by_contra h2a_ne
          -- if 2a ≠ 0 then 2a • u_add = 0 ⇒ u_add = 0 (since (ZMod p) is a field)
          have : u_add = 0 := by
            have h_inv : (2 * a)⁻¹ * (2 * a) = 1 := inv_mul_cancel₀ h2a_ne
            calc u_add = ((2 * a)⁻¹ * (2 * a)) • u_add := by rw [h_inv, one_smul]
              _ = (2 * a)⁻¹ • ((2 * a) • u_add) := by rw [mul_smul]
              _ = (2 * a)⁻¹ • (0 : Additive H) := by rw [h_sum]
              _ = 0 := smul_zero _
          exact hu_add_ne this
        rcases mul_eq_zero.mp h2a with h | h
        · exact absurd h h2_ne_zero
        · exact h
      have hb : b = 0 := by
        have h2b : (2 * b) = 0 := by
          by_contra h2b_ne
          have : v_add = 0 := by
            have h_inv : (2 * b)⁻¹ * (2 * b) = 1 := inv_mul_cancel₀ h2b_ne
            calc v_add = ((2 * b)⁻¹ * (2 * b)) • v_add := by rw [h_inv, one_smul]
              _ = (2 * b)⁻¹ • ((2 * b) • v_add) := by rw [mul_smul]
              _ = (2 * b)⁻¹ • (0 : Additive H) := by rw [h_sub]
              _ = 0 := smul_zero _
          exact hv_add_ne this
        rcases mul_eq_zero.mp h2b with h | h
        · exact absurd h h2_ne_zero
        · exact h
      exact ⟨ha, hb⟩
    -- Step 4: Build the basis. First, prove u and v generate H.
    -- We'll show via linear algebra that they span Additive H, hence generate H multiplicatively.
    let b_std : Module.Basis (Fin 2) (ZMod p) (Fin 2 → ZMod p) := Pi.basisFun (ZMod p) (Fin 2)
    let φ_map : (Fin 2 → ZMod p) →ₗ[ZMod p] Additive H :=
      b_std.constr (ZMod p) ![u_add, v_add]
    -- φ_map is injective (kernel is 0)
    have h_φ_map_e₀ : φ_map (b_std 0) = u_add := by
      change b_std.constr (ZMod p) ![u_add, v_add] (b_std 0) = _
      rw [Module.Basis.constr_basis]; rfl
    have h_φ_map_e₁ : φ_map (b_std 1) = v_add := by
      change b_std.constr (ZMod p) ![u_add, v_add] (b_std 1) = _
      rw [Module.Basis.constr_basis]; rfl
    have h_e₀ : (b_std 0 : Fin 2 → ZMod p) = ![1, 0] := by
      ext i; fin_cases i <;> simp [b_std, Pi.basisFun_apply, Pi.single]
    have h_e₁ : (b_std 1 : Fin 2 → ZMod p) = ![0, 1] := by
      ext i; fin_cases i <;> simp [b_std, Pi.basisFun_apply, Pi.single]
    -- φ_map applied to general vector
    have h_φ_map_apply : ∀ (a b : ZMod p),
        φ_map (![a, b] : Fin 2 → ZMod p) = a • u_add + b • v_add := by
      intro a b
      have h_decomp :
          (![a, b] : Fin 2 → ZMod p) =
          a • (b_std 0 : Fin 2 → ZMod p) + b • (b_std 1 : Fin 2 → ZMod p) := by
        ext i; fin_cases i <;> simp [b_std, Pi.basisFun_apply, Pi.single]
      rw [h_decomp, map_add, LinearMap.map_smul, LinearMap.map_smul,
          h_φ_map_e₀, h_φ_map_e₁]
    have h_inj : Function.Injective φ_map := by
      rw [← LinearMap.ker_eq_bot]
      rw [eq_bot_iff]
      intro v hv
      rw [LinearMap.mem_ker] at hv
      -- v : Fin 2 → ZMod p ; φ_map v = 0
      have hv_eq : v = ![v 0, v 1] := by
        ext i; fin_cases i <;> rfl
      rw [hv_eq, h_φ_map_apply] at hv
      obtain ⟨h0, h1⟩ := h_lin_indep _ _ hv
      rw [Submodule.mem_bot]
      ext i; fin_cases i
      · exact h0
      · exact h1
    have h_finrank_pi : Module.finrank (ZMod p) (Fin 2 → ZMod p) = 2 := by
      rw [Module.finrank_pi]; rfl
    have h_finrank_eq : Module.finrank (ZMod p) (Fin 2 → ZMod p) =
        Module.finrank (ZMod p) (Additive H) := by
      rw [h_finrank_pi, h_finrank_addH]
    haveI h_findim_pi : FiniteDimensional (ZMod p) (Fin 2 → ZMod p) := inferInstance
    haveI h_findim_addH : FiniteDimensional (ZMod p) (Additive H) :=
      Module.finite_of_finrank_eq_succ h_finrank_addH
    have h_surj : Function.Surjective φ_map :=
      (LinearMap.injective_iff_surjective_of_finrank_eq_finrank h_finrank_eq).mp h_inj
    -- Build the linear equiv φ : (Fin 2 → ZMod p) ≃ₗ[ZMod p] Additive H
    let φ : (Fin 2 → ZMod p) ≃ₗ[ZMod p] Additive H :=
      LinearEquiv.ofBijective φ_map ⟨h_inj, h_surj⟩
    -- u, v generate H multiplicatively
    have h_gen_uv : Subgroup.zpowers u ⊔ Subgroup.zpowers v = ⊤ := by
      rw [eq_top_iff]
      intro h _
      -- write Additive.ofMul h = a • u_add + b • v_add via surjectivity of φ_map
      obtain ⟨vec, hvec⟩ := h_surj (Additive.ofMul h)
      have hvec_eq : vec = ![vec 0, vec 1] := by ext i; fin_cases i <;> rfl
      have h_decomp : Additive.ofMul h = vec 0 • u_add + vec 1 • v_add := by
        calc Additive.ofMul h = φ_map vec := hvec.symm
          _ = φ_map ![vec 0, vec 1] := by rw [← hvec_eq]
          _ = vec 0 • u_add + vec 1 • v_add := h_φ_map_apply (vec 0) (vec 1)
      -- Convert (r : ZMod p) • x to (r.val : ℤ) • x for both terms
      have h_smul_u : (vec 0) • u_add = ((vec 0).val : ℤ) • u_add := by
        rw [← Int.cast_smul_eq_zsmul (ZMod p), Int.cast_natCast, ZMod.natCast_zmod_val]
      have h_smul_v : (vec 1) • v_add = ((vec 1).val : ℤ) • v_add := by
        rw [← Int.cast_smul_eq_zsmul (ZMod p), Int.cast_natCast, ZMod.natCast_zmod_val]
      -- Now convert to multiplicative form
      have h_mul : h = u ^ ((vec 0).val : ℤ) * v ^ ((vec 1).val : ℤ) := by
        apply Additive.ofMul.injective
        rw [h_decomp, h_smul_u, h_smul_v, ofMul_mul, ← ofMul_zpow, ← ofMul_zpow]
      rw [h_mul]
      exact mul_mem
        (Subgroup.mem_sup_left (Subgroup.zpow_mem _ (Subgroup.mem_zpowers u) _))
        (Subgroup.mem_sup_right (Subgroup.zpow_mem _ (Subgroup.mem_zpowers v) _))
    -- Step 5: build β : MulAut H from φ
    let β_lin : Additive H ≃ₗ[ZMod p] Additive H := by
      -- We want β maps the basis elements (1,0), (0,1) of Additive H to u_add, v_add
      -- but β : Additive H ≃ Additive H. We use φ to build β.
      -- Actually, β should send (Multiplicative.ofAdd 1, 1) to u and (1, Multiplicative.ofAdd 1) to v
      -- We use Additive H ≃ₗ Fin 2 → ZMod p built differently...
      -- Let's use φ : (Fin 2 → ZMod p) ≃ₗ Additive H. We also need
      -- another equiv ψ_std : (Fin 2 → ZMod p) ≃ₗ Additive H mapping (1,0) ↦ (e₁, 0), (0,1) ↦ (0, e₂)
      -- where e₁, e₂ are the standard generators.
      -- For simplicity, just build φ_lin (as defined above).
      exact φ.symm.trans φ
    -- We don't actually use β_lin this way. Let's reconstruct: we want
    -- β : MulAut H with β g₁ = u, β g₂ = v where
    -- g₁ := (Multiplicative.ofAdd 1, 1), g₂ := (1, Multiplicative.ofAdd 1)
    -- Define standard equiv std_φ : (Fin 2 → ZMod p) ≃ₗ Additive H by (1,0) ↦ Additive.ofMul g₁,
    -- (0,1) ↦ Additive.ofMul g₂
    set g₁ : H := (Multiplicative.ofAdd (1 : ZMod p), 1) with hg₁_def
    set g₂ : H := (1, Multiplicative.ofAdd (1 : ZMod p)) with hg₂_def
    let g₁_add : Additive H := Additive.ofMul g₁
    let g₂_add : Additive H := Additive.ofMul g₂
    -- Check that g₁, g₂ generate H
    have h_gen_g : Subgroup.zpowers g₁ ⊔ Subgroup.zpowers g₂ = ⊤ := by
      rw [eq_top_iff]
      rintro ⟨a, b⟩ _
      -- Express (a, b) as g₁^? * g₂^?. With g = Multiplicative.ofAdd (1 : ZMod p)
      -- being a generator of CyclicGroup p, we have a = g^i, b = g^j, so
      -- (a, b) = (g^i, 1) * (1, g^j) = g₁^i * g₂^j
      have h_card_cp : Nat.card (CyclicGroup p) = p := card_cyclicGroup p
      obtain ⟨gcp, hgcp⟩ := IsCyclic.exists_generator (α := CyclicGroup p)
      have hgcp_order : orderOf gcp = p := by
        rw [orderOf_eq_card_of_forall_mem_zpowers hgcp, h_card_cp]
      -- Establish that Multiplicative.ofAdd 1 generates CyclicGroup p
      have h_ofAdd_gen : ∀ x : CyclicGroup p, x ∈ Subgroup.zpowers
          (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p) := by
        intro x
        refine Subgroup.mem_zpowers_iff.mpr
          ⟨((Multiplicative.toAdd x).val : ℤ), ?_⟩
        show Multiplicative.ofAdd (1 : ZMod p) ^ ((Multiplicative.toAdd x).val : ℤ) = x
        rw [← Multiplicative.ofAdd.apply_symm_apply x]
        show Multiplicative.ofAdd (1 : ZMod p) ^ ((Multiplicative.toAdd x).val : ℤ)
            = Multiplicative.ofAdd (Multiplicative.toAdd x)
        rw [← ofAdd_zsmul, zsmul_one]
        congr 1
        push_cast
        exact ZMod.natCast_zmod_val _
      obtain ⟨i, hi⟩ := Subgroup.mem_zpowers_iff.mp (h_ofAdd_gen a)
      obtain ⟨j, hj⟩ := Subgroup.mem_zpowers_iff.mp (h_ofAdd_gen b)
      have h_g₁_pow : (g₁ ^ i : H) = (a, 1) := by
        have : (g₁ ^ i : H) = (g₁.1 ^ i, g₁.2 ^ i) := rfl
        rw [this]
        refine Prod.ext ?_ ?_
        · show (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p) ^ i = a
          exact hi
        · show (1 : CyclicGroup p) ^ i = 1
          exact one_zpow i
      have h_g₂_pow : (g₂ ^ j : H) = (1, b) := by
        have : (g₂ ^ j : H) = (g₂.1 ^ j, g₂.2 ^ j) := rfl
        rw [this]
        refine Prod.ext ?_ ?_
        · show (1 : CyclicGroup p) ^ j = 1
          exact one_zpow j
        · show (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p) ^ j = b
          exact hj
      have hab_eq : (a, b) = g₁ ^ i * g₂ ^ j := by
        rw [h_g₁_pow, h_g₂_pow, Prod.mk_mul_mk, mul_one, one_mul]
      rw [hab_eq]
      exact mul_mem
        (Subgroup.mem_sup_left (Subgroup.zpow_mem _ (Subgroup.mem_zpowers g₁) _))
        (Subgroup.mem_sup_right (Subgroup.zpow_mem _ (Subgroup.mem_zpowers g₂) _))
    let std_map : (Fin 2 → ZMod p) →ₗ[ZMod p] Additive H :=
      b_std.constr (ZMod p) ![g₁_add, g₂_add]
    have h_std_map_e₀ : std_map (b_std 0) = g₁_add := by
      change b_std.constr (ZMod p) ![g₁_add, g₂_add] (b_std 0) = _
      rw [Module.Basis.constr_basis]; rfl
    have h_std_map_e₁ : std_map (b_std 1) = g₂_add := by
      change b_std.constr (ZMod p) ![g₁_add, g₂_add] (b_std 1) = _
      rw [Module.Basis.constr_basis]; rfl
    have h_std_map_apply : ∀ (a b : ZMod p),
        std_map (![a, b] : Fin 2 → ZMod p) = a • g₁_add + b • g₂_add := by
      intro a b
      have h_decomp :
          (![a, b] : Fin 2 → ZMod p) =
          a • (b_std 0 : Fin 2 → ZMod p) + b • (b_std 1 : Fin 2 → ZMod p) := by
        ext i; fin_cases i <;> simp [b_std, Pi.basisFun_apply, Pi.single]
      rw [h_decomp, map_add, LinearMap.map_smul, LinearMap.map_smul,
          h_std_map_e₀, h_std_map_e₁]
    -- std_map is surjective using g₁, g₂ generating
    have h_std_surj : LinearMap.range std_map = ⊤ := by
      rw [eq_top_iff]
      intro h _
      have h_mem : Additive.toMul h ∈ Subgroup.zpowers g₁ ⊔ Subgroup.zpowers g₂ :=
        h_gen_g ▸ Subgroup.mem_top _
      rw [Subgroup.mem_sup] at h_mem
      obtain ⟨x, hx_mem, y, hy_mem, hxy⟩ := h_mem
      obtain ⟨a, ha⟩ := Subgroup.mem_zpowers_iff.mp hx_mem
      obtain ⟨b, hb⟩ := Subgroup.mem_zpowers_iff.mp hy_mem
      have h_mul : Additive.toMul h = g₁ ^ a * g₂ ^ b := by rw [← hxy, ha, hb]
      have h_add : h = (a : ℤ) • g₁_add + (b : ℤ) • g₂_add := by
        have hzpow_g₁ : Additive.ofMul (g₁ ^ a) = (a : ℤ) • g₁_add := ofMul_zpow a g₁
        have hzpow_g₂ : Additive.ofMul (g₂ ^ b) = (b : ℤ) • g₂_add := ofMul_zpow b g₂
        have h_id : Additive.ofMul (Additive.toMul h) = h := rfl
        rw [← h_id, h_mul, ofMul_mul, hzpow_g₁, hzpow_g₂]
      refine ⟨![(a : ZMod p), (b : ZMod p)], ?_⟩
      rw [h_std_map_apply, h_add]
      rw [Int.cast_smul_eq_zsmul, Int.cast_smul_eq_zsmul]
    have h_std_inj : Function.Injective std_map :=
      (LinearMap.injective_iff_surjective_of_finrank_eq_finrank h_finrank_eq).mpr
        (LinearMap.range_eq_top.mp h_std_surj)
    let std_φ : (Fin 2 → ZMod p) ≃ₗ[ZMod p] Additive H :=
      LinearEquiv.ofBijective std_map ⟨h_std_inj, LinearMap.range_eq_top.mp h_std_surj⟩
    -- Now build β_eq : Additive H ≃ₗ Additive H sending g₁_add ↦ u_add, g₂_add ↦ v_add
    let β_eq : Additive H ≃ₗ[ZMod p] Additive H := std_φ.symm.trans φ
    -- β_eq sends g_1_add ↦ u_add, g_2_add ↦ v_add
    have h_std_φ_e₀ : std_φ (b_std 0) = g₁_add := by
      change std_map (b_std 0) = g₁_add; exact h_std_map_e₀
    have h_std_φ_e₁ : std_φ (b_std 1) = g₂_add := by
      change std_map (b_std 1) = g₂_add; exact h_std_map_e₁
    have h_std_φ_inv_g₁ : std_φ.symm g₁_add = b_std 0 := by
      rw [← h_std_φ_e₀]; exact std_φ.symm_apply_apply (b_std 0)
    have h_std_φ_inv_g₂ : std_φ.symm g₂_add = b_std 1 := by
      rw [← h_std_φ_e₁]; exact std_φ.symm_apply_apply (b_std 1)
    have h_β_eq_g₁ : β_eq g₁_add = u_add := by
      change φ (std_φ.symm g₁_add) = u_add
      rw [h_std_φ_inv_g₁]
      change φ_map (b_std 0) = u_add
      exact h_φ_map_e₀
    have h_β_eq_g₂ : β_eq g₂_add = v_add := by
      change φ (std_φ.symm g₂_add) = v_add
      rw [h_std_φ_inv_g₂]
      change φ_map (b_std 1) = v_add
      exact h_φ_map_e₁
    -- Build β : MulAut H
    let β_add : Additive H ≃+ Additive H := β_eq.toAddEquiv
    let β : MulAut H := AddAutAdditive (G := H) β_add
    -- β g₁ = u, β g₂ = v
    have h_β_g₁ : β g₁ = u := by
      change β.toMonoidHom g₁ = u
      have h : β_add g₁_add = u_add := h_β_eq_g₁
      change Additive.toMul (β_add (Additive.ofMul g₁)) = u
      rw [h]; rfl
    have h_β_g₂ : β g₂ = v := by
      change β.toMonoidHom g₂ = v
      have h : β_add g₂_add = v_add := h_β_eq_g₂
      change Additive.toMul (β_add (Additive.ofMul g₂)) = v
      rw [h]; rfl
    -- Conclude: β * cpcpInvSecond p * β⁻¹ = σ
    -- Use isConj_iff: IsConj a b ↔ ∃ c, c * a * c⁻¹ = b
    rw [isConj_iff]
    refine ⟨β, ?_⟩
    -- Goal: β * cpcpInvSecond p * β⁻¹ = σ
    -- Equivalent to β * cpcpInvSecond p = σ * β
    rw [mul_inv_eq_iff_eq_mul]
    show β * cpcpInvSecond p = σ * β
    -- Verify on generators g₁ and g₂
    have h_at_g₁ : (β * cpcpInvSecond p) g₁ = (σ * β) g₁ := by
      rw [MulAut.mul_apply, MulAut.mul_apply]
      show β (cpcpInvSecond p g₁) = σ (β g₁)
      have h_inv_g₁ : cpcpInvSecond p g₁ = g₁ := by
        show ((g₁.1, g₁.2⁻¹) : H) = g₁
        refine Prod.ext rfl ?_
        change (g₁.2 : CyclicGroup p)⁻¹ = g₁.2
        rw [hg₁_def]
        exact inv_one
      rw [h_inv_g₁, h_β_g₁, hu_fixed]
    have h_at_g₂ : (β * cpcpInvSecond p) g₂ = (σ * β) g₂ := by
      rw [MulAut.mul_apply, MulAut.mul_apply]
      show β (cpcpInvSecond p g₂) = σ (β g₂)
      have h_inv_g₂ : cpcpInvSecond p g₂ = g₂⁻¹ := by
        show ((g₂.1, g₂.2⁻¹) : H) = g₂⁻¹
        change ((1 : CyclicGroup p), (Multiplicative.ofAdd (1 : ZMod p))⁻¹) =
          ((1 : CyclicGroup p)⁻¹, (Multiplicative.ofAdd (1 : ZMod p))⁻¹)
        simp
      rw [h_inv_g₂, map_inv, h_β_g₂, hv_inv]
    -- Extract pointwise equalities from h_at_g₁, h_at_g₂
    have hβσ_g₁ : β (cpcpInvSecond p g₁) = σ (β g₁) := by
      have := h_at_g₁
      rwa [MulAut.mul_apply, MulAut.mul_apply] at this
    have hβσ_g₂ : β (cpcpInvSecond p g₂) = σ (β g₂) := by
      have := h_at_g₂
      rwa [MulAut.mul_apply, MulAut.mul_apply] at this
    -- Now show β * cpcpInvSecond p = σ * β by checking they agree on H
    -- It suffices to check on g₁ and g₂ since they generate H
    apply MulEquiv.ext
    intro x
    -- Express x = g₁^a * g₂^b
    have hx_mem : x ∈ Subgroup.zpowers g₁ ⊔ Subgroup.zpowers g₂ :=
      h_gen_g ▸ Subgroup.mem_top x
    rw [Subgroup.mem_sup] at hx_mem
    obtain ⟨w₁, hw₁_mem, w₂, hw₂_mem, hw_eq⟩ := hx_mem
    obtain ⟨a, ha⟩ := Subgroup.mem_zpowers_iff.mp hw₁_mem
    obtain ⟨b, hb⟩ := Subgroup.mem_zpowers_iff.mp hw₂_mem
    have hx_eq : x = g₁ ^ a * g₂ ^ b := by rw [← hw_eq, ha, hb]
    rw [hx_eq]
    show (β * cpcpInvSecond p) (g₁ ^ a * g₂ ^ b) = (σ * β) (g₁ ^ a * g₂ ^ b)
    rw [MulAut.mul_apply, MulAut.mul_apply]
    show β (cpcpInvSecond p (g₁ ^ a * g₂ ^ b)) = σ (β (g₁ ^ a * g₂ ^ b))
    rw [map_mul (cpcpInvSecond p), map_mul β, map_mul β, map_mul σ,
        map_zpow (cpcpInvSecond p), map_zpow (cpcpInvSecond p),
        map_zpow β, map_zpow β, map_zpow β, map_zpow β,
        map_zpow σ, map_zpow σ, hβσ_g₁, hβσ_g₂]

/-! ## Range cards for the new canonical actions. -/

/-- The order of `cpcpInvSecond p` is exactly 2 (provided p ≠ 2). -/
lemma orderOf_cpcpInvSecond {p : ℕ} [hp : Fact p.Prime] (hp_ne_2 : p ≠ 2) :
    orderOf (cpcpInvSecond p) = 2 := by
  haveI : NeZero p := ⟨hp.out.pos.ne'⟩
  refine orderOf_eq_prime (cpcpInvSecond_sq p) ?_
  intro h
  -- (cpcpInvSecond p) = 1 ⇒ on the pair (1, ofAdd 1), second coord inverts to itself.
  have h_app := congr_fun (congr_arg DFunLike.coe h)
    ((1 : CyclicGroup p), (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p))
  have h_eq : ((1 : CyclicGroup p), (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)⁻¹) =
      ((1 : CyclicGroup p), (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)) := h_app
  have h_inv : (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)⁻¹ =
      (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p) :=
    (Prod.mk.injEq _ _ _ _).mp h_eq |>.2
  -- This gives 1 = -1 in ZMod p, hence p ∣ 2, hence p = 2.
  have h_zmod_eq : (-1 : ZMod p) = (1 : ZMod p) := by
    have : (Multiplicative.ofAdd (-(1 : ZMod p)) : CyclicGroup p) =
        (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p) := by
      rw [show (Multiplicative.ofAdd (-(1 : ZMod p)) : CyclicGroup p) =
        (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)⁻¹ from rfl]
      exact h_inv
    exact (Multiplicative.ofAdd.injective this)
  -- (-1 : ZMod p) = 1 means 2 ≡ 0 (mod p), hence p ∣ 2, hence p = 2.
  have h_two_zero : (2 : ZMod p) = 0 := by linear_combination -h_zmod_eq
  -- p ∣ 2 because (2 : ZMod p) = 0
  have h_two_cast : ((2 : ℕ) : ZMod p) = 0 := by exact_mod_cast h_two_zero
  have h_p_dvd : p ∣ 2 := (ZMod.natCast_eq_zero_iff 2 p).mp h_two_cast
  have h_p_eq : p = 2 :=
    (Nat.prime_dvd_prime_iff_eq hp.out Nat.prime_two).mp h_p_dvd
  exact hp_ne_2 h_p_eq

/-- The order of `cpcpInvBoth p` is exactly 2 (provided p ≠ 2). -/
lemma orderOf_cpcpInvBoth {p : ℕ} [hp : Fact p.Prime] (hp_ne_2 : p ≠ 2) :
    orderOf (cpcpInvBoth p) = 2 := by
  haveI : NeZero p := ⟨hp.out.pos.ne'⟩
  refine orderOf_eq_prime (cpcpInvBoth_sq p) ?_
  intro h
  have h_app := congr_fun (congr_arg DFunLike.coe h)
    ((Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p), (1 : CyclicGroup p))
  have h_eq : ((Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)⁻¹,
      (1 : CyclicGroup p)⁻¹) =
      ((Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p), (1 : CyclicGroup p)) := h_app
  have h_inv : (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)⁻¹ =
      (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p) :=
    (Prod.mk.injEq _ _ _ _).mp h_eq |>.1
  have h_zmod_eq : (-1 : ZMod p) = (1 : ZMod p) := by
    have : (Multiplicative.ofAdd (-(1 : ZMod p)) : CyclicGroup p) =
        (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p) := by
      rw [show (Multiplicative.ofAdd (-(1 : ZMod p)) : CyclicGroup p) =
        (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)⁻¹ from rfl]
      exact h_inv
    exact (Multiplicative.ofAdd.injective this)
  have h_two_zero : (2 : ZMod p) = 0 := by linear_combination -h_zmod_eq
  have h_two_cast : ((2 : ℕ) : ZMod p) = 0 := by exact_mod_cast h_two_zero
  have h_p_dvd : p ∣ 2 := (ZMod.natCast_eq_zero_iff 2 p).mp h_two_cast
  exact hp_ne_2 ((Nat.prime_dvd_prime_iff_eq hp.out Nat.prime_two).mp h_p_dvd)

lemma canonicalC2OnCpCpAction_r1_range_card {p : ℕ} [hp : Fact p.Prime] (hp_ne_2 : p ≠ 2) :
    Nat.card (canonicalC2OnCpCpAction_r1 p).range = 2 := by
  haveI : NeZero p := ⟨hp.out.pos.ne'⟩
  show Nat.card (cyclicHom 2 (cpcpInvSecond p) (cpcpInvSecond_sq p)).range = 2
  rw [cyclicHom_range, Nat.card_zpowers, orderOf_cpcpInvSecond hp_ne_2]

lemma canonicalC2OnCpCpAction_r2_range_card {p : ℕ} [hp : Fact p.Prime] (hp_ne_2 : p ≠ 2) :
    Nat.card (canonicalC2OnCpCpAction_r2 p).range = 2 := by
  haveI : NeZero p := ⟨hp.out.pos.ne'⟩
  show Nat.card (cyclicHom 2 (cpcpInvBoth p) (cpcpInvBoth_sq p)).range = 2
  rw [cyclicHom_range, Nat.card_zpowers, orderOf_cpcpInvBoth hp_ne_2]

/-! ## Main classification of groups of order `2p^2`. -/

set_option maxHeartbeats 400000 in
theorem classification_2p2 {p : ℕ} [h_p_prime : Fact p.Prime] [Group G]
    (h_ge_3 : p ≥ 3) (h : Nat.card G = p ^ 2 * 2)
    : Nonempty (G ≃* CyclicGroup (2 * p ^ 2))
      ∨ Nonempty (G ≃* CyclicGroup p × CyclicGroup p × CyclicGroup 2)
      ∨ Nonempty (G ≃* SemidirectProduct (CyclicGroup (p ^ 2)) (CyclicGroup 2)
                         (canonicalC2OnCp2Action (by omega : p ≠ 2)))
      ∨ Nonempty (G ≃* SemidirectProduct (CyclicGroup p × CyclicGroup p) (CyclicGroup 2)
                         (canonicalC2OnCpCpAction_r1 p))
      ∨ Nonempty (G ≃* SemidirectProduct (CyclicGroup p × CyclicGroup p) (CyclicGroup 2)
                         (canonicalC2OnCpCpAction_r2 p)) := by
  haveI : NeZero p := ⟨h_p_prime.out.ne_zero⟩
  haveI : Fact (Nat.Prime 2) := ⟨by norm_num⟩
  have hp_ne_2 : p ≠ 2 := by omega
  haveI : Finite G := by
    apply Nat.finite_of_card_ne_zero; rw [h]
    have p_ne : p ≠ 0 := Nat.Prime.ne_zero h_p_prime.elim
    simp; tauto
  let n_p := Nat.card (Sylow p G)
  let n_2 := Nat.card (Sylow 2 G)
  have hpne2 : p ≠ 2 := hp_ne_2
  have n_p_or_n_2_one : n_p = 1 ∨ n_2 = 1 :=
    p2q_group_has_normal_sylow_subgroup G hpne2 h
  have h2cop : Nat.Coprime 2 p :=
    ((by norm_num : (2 : ℕ).Prime).coprime_of_ne h_p_prime.out (by omega))
  have h_p2_p_card : Nat.card G = p ^ 2 * 2 ^ 1 := by simpa using h
  have h_2_p2_card : Nat.card G = 2 ^ 1 * p ^ 2 := by rw [h]; ring
  rcases n_p_or_n_2_one with h_np_1 | h_n2_1
  · -- n_p = 1: Sylow p-subgroup N (order p²) is normal, complement K of order 2
    let N : Sylow p G := default
    haveI : Subsingleton (Sylow p G) := (Nat.card_eq_one_iff_unique.mp h_np_1).1
    have h_N_card : Nat.card ↥(N : Subgroup G) = p ^ 2 :=
      sylow_card_eq hpne2 h_p2_p_card N
    have h_N_idx_2 : ∀ N : Sylow p G, (↑N : Subgroup G).index = 2 := fun N => by
      simpa using sylow_index_eq hpne2 h_p2_p_card N
    obtain ⟨K, hK⟩ := Subgroup.exists_right_complement'_of_coprime
      (N := (↑N : Subgroup G)) (by
      rw [h_N_card, h_N_idx_2]
      exact ((h_p_prime.out.coprime_of_ne (by norm_num : (2 : ℕ).Prime) hpne2)).pow_left 2)
    have h_iso_g_n_k := SemidirectProduct.mulEquivSubgroup hK
    let φ : ↥K →* MulAut ↥(↑N : Subgroup G) :=
      (↑N : Subgroup G).normalizerMonoidHom.comp
        (Subgroup.inclusion (by simp [Subgroup.normalizer_eq_top]))
    have hK_card : Nat.card ↥K = 2 := by
      have h1 : Nat.card G = Nat.card ↥(↑N : Subgroup G) * Nat.card ↥K := by
        have heq := Nat.card_congr h_iso_g_n_k.toEquiv
        rw [SemidirectProduct.card] at heq; exact heq.symm
      rw [h_N_card, h] at h1
      have hp_pos : 0 < p ^ 2 := pow_pos h_p_prime.out.pos 2
      exact (Nat.eq_of_mul_eq_mul_left hp_pos h1).symm
    have eK : ↥K ≃* CyclicGroup 2 :=
      Classical.choice (prime_classification_of_group (n := 2) hK_card)
    have h2p2cop : Nat.Coprime 2 (p ^ 2) := h2cop.pow_right 2
    have hp2_2cop : Nat.Coprime (p ^ 2) 2 := h2p2cop.symm
    rcases (p_squared_classification (p := p) h_N_card) with h_N_Cp2 | h_N_CpCp
    · -- N ≅ C_{p²}: bridge φ via eN, eK, dispatch via classify_Cqn_rtimes_Cpm
      let eN := h_N_Cp2.some
      let φ_inter : CyclicGroup 2 →* MulAut (CyclicGroup (p ^ 2)) :=
        (MulAut.congr eN).toMonoidHom.comp (φ.comp eK.symm.toMonoidHom)
      have h_congr : ↥(↑N : Subgroup G) ⋊[φ] ↥K ≃*
          SemidirectProduct (CyclicGroup (p ^ 2)) (CyclicGroup 2) φ_inter :=
        SemidirectProduct.congr' (φ₁ := φ) (fn := eN) (fg := eK)
      haveI : NeZero (p ^ 2) := ⟨pow_ne_zero 2 h_p_prime.out.ne_zero⟩
      haveI : NeZero ((2:ℕ)^1) := ⟨pow_ne_zero 1 (by norm_num)⟩
      have h2p : (2 : ℕ) ≠ p := by omega
      have h21 : ((2:ℕ)^1 : ℕ) = 2 := by norm_num
      have hp22 : (p^2 : ℕ) = p^2 := rfl
      have h_pre_iso := SemidirectProduct.transportCpCqIso h21.symm hp22.symm φ_inter
      obtain ⟨⟨r, hr_lt⟩, ⟨e_pre⟩, _⟩ := classify_Cqn_rtimes_Cpm (p := 2) (q := p) h2p hpne2 1 2
        Nat.one_pos (by norm_num)
        (transportCpCqHom h21.symm hp22.symm φ_inter)
      have hr_le : r ≤ min 1 ((p - 1).factorization 2) := Nat.lt_succ_iff.mp hr_lt
      let canonR := fun r (hr : r ≤ min 1 ((p - 1).factorization 2)) =>
        canonicalAction 2 p 2 1 h2p hpne2 (by norm_num) r hr
      let e_back := fun r hr => SemidirectProduct.transportCpCqIso h21 hp22 (canonR r hr)
      let pre := h_iso_g_n_k.symm.trans (h_congr.trans (h_pre_iso.trans
        (e_pre.trans (e_back r hr_le))))
      have hr_le_1 : r ≤ 1 := hr_le.trans (min_le_left _ _)
      interval_cases r
      · -- r = 0: trivial action → G ≃* C_{2p²}
        have h_triv := eq_one_of_range_card_one (by
          show Nat.card (transportCpCqHom h21 hp22 (canonR 0 hr_le)).range = 1
          rw [transportCpCqHom_range_card]
          simpa using canonicalAction_range_card 2 p 2 1 0 h2p hpne2 (by norm_num) hr_le)
        have : G ≃* CyclicGroup (2 * p ^ 2) := pre.trans
          ((SemidirectProduct.mulEquivOfTrivialAction h_triv).trans
            (MulEquiv.prodComm.trans (CyclicGroup.prodMulEquiv h2p2cop)))
        tauto
      · -- r = 1: matches `canonicalC2OnCp2Action`.
        tauto
    · -- N ≅ C_p × C_p: by_cases on φ_inter triviality
      let eN := h_N_CpCp.some
      let φ_inter : CyclicGroup 2 →* MulAut (CyclicGroup p × CyclicGroup p) :=
        (MulAut.congr eN).toMonoidHom.comp (φ.comp eK.symm.toMonoidHom)
      have h_congr : ↥(↑N : Subgroup G) ⋊[φ] ↥K ≃*
          SemidirectProduct (CyclicGroup p × CyclicGroup p) (CyclicGroup 2) φ_inter :=
        SemidirectProduct.congr' (φ₁ := φ) (fn := eN) (fg := eK)
      by_cases h_triv : φ_inter = 1
      · -- φ_inter trivial → G ≃* (C_p × C_p) × C_2
        have : G ≃* CyclicGroup p × CyclicGroup p × CyclicGroup 2 :=
          h_iso_g_n_k.symm.trans (h_congr.trans
            ((SemidirectProduct.mulEquivOfTrivialAction h_triv).trans
              MulEquiv.prodAssoc))
        tauto
      · -- φ_inter nontrivial: image has order 2 by Lagrange (|C_2| = 2 prime)
        -- so φ_inter is determined by a single order-2 σ; conjugate to canon₁ or canon₂.
        -- φ_inter(generator) has order dividing 2; nontriviality forces it to be 2.
        have h_card_K2 : Nat.card (CyclicGroup 2) = 2 := card_cyclicGroup 2
        -- |φ_inter.range| divides |C_2| = 2, and isn't 1.
        have h_range_dvd : Nat.card φ_inter.range ∣ 2 := by
          have := Subgroup.card_range_dvd φ_inter; rwa [h_card_K2] at this
        have h_range_ne_1 : Nat.card φ_inter.range ≠ 1 :=
          fun h => h_triv (eq_one_of_range_card_one h)
        have h_range_card : Nat.card φ_inter.range = 2 := by
          rcases (Nat.dvd_prime Nat.prime_two).mp h_range_dvd with h1 | h2
          · exact absurd h1 h_range_ne_1
          · exact h2
        -- the generator (Multiplicative.ofAdd 1 : CyclicGroup 2) maps to some σ
        let g₂ : CyclicGroup 2 := Multiplicative.ofAdd (1 : ZMod 2)
        let σ : MulAut (CyclicGroup p × CyclicGroup p) := φ_inter g₂
        have hg2_sq : g₂ ^ 2 = 1 := by
          have h := pow_card_eq_one' (G := CyclicGroup 2) (x := g₂)
          rwa [card_cyclicGroup] at h
        have hσ_sq : σ ^ 2 = 1 := by
          have := congr_arg φ_inter hg2_sq
          rwa [map_pow, map_one] at this
        -- σ ≠ 1: otherwise φ_inter would be trivial since g₂ generates.
        have hg₂_gen : ∀ x : CyclicGroup 2, x ∈ Subgroup.zpowers g₂ := by
          intro x
          refine Subgroup.mem_zpowers_iff.mpr ⟨((Multiplicative.toAdd x).val : ℤ), ?_⟩
          show Multiplicative.ofAdd (1 : ZMod 2) ^ ((Multiplicative.toAdd x).val : ℤ) = x
          rw [← Multiplicative.ofAdd.apply_symm_apply x]
          show Multiplicative.ofAdd (1 : ZMod 2) ^ ((Multiplicative.toAdd x).val : ℤ)
              = Multiplicative.ofAdd (Multiplicative.toAdd x)
          rw [← ofAdd_zsmul, zsmul_one]
          congr 1
          push_cast
          exact ZMod.natCast_zmod_val _
        have hσ_ne_one : σ ≠ 1 := by
          intro hσ1
          apply h_triv
          have hext : ∀ x : CyclicGroup 2, φ_inter x = 1 := by
            intro x
            obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp (hg₂_gen x)
            have : φ_inter x = (φ_inter g₂) ^ n := by rw [← hn, map_zpow]
            rw [this, show φ_inter g₂ = σ from rfl, hσ1, one_zpow]
          ext x : 1; rw [hext x]; rfl
        have hσ_order : orderOf σ = 2 := orderOf_eq_prime hσ_sq hσ_ne_one
        -- Apply mulAut_cpcp_order_two_conj.
        -- Helper: cyclicHom evaluated at g₂ gives the underlying element.
        have hval_g₂ : ((Multiplicative.toAdd g₂).val : ℤ) = 1 := by
          change ((1 : ZMod 2).val : ℤ) = 1
          rw [ZMod.val_one_eq_one_mod]; norm_num
        have h_r1_g₂ : canonicalC2OnCpCpAction_r1 p g₂ = cpcpInvSecond p := by
          show (cyclicHom 2 (cpcpInvSecond p) (cpcpInvSecond_sq p)) g₂ = cpcpInvSecond p
          rw [cyclicHom_apply_eq_zpow, hval_g₂]; exact zpow_one _
        have h_r2_g₂ : canonicalC2OnCpCpAction_r2 p g₂ = cpcpInvBoth p := by
          show (cyclicHom 2 (cpcpInvBoth p) (cpcpInvBoth_sq p)) g₂ = cpcpInvBoth p
          rw [cyclicHom_apply_eq_zpow, hval_g₂]; exact zpow_one _
        rcases mulAut_cpcp_order_two_conj hp_ne_2 σ hσ_order with h_conj1 | h_conj2
        · -- σ is conjugate to cpcpInvSecond p, hence φ_inter ≅ canonicalC2OnCpCpAction_r1 p
          obtain ⟨cu, hcu⟩ := h_conj1
          -- hcu : SemiconjBy (↑cu) (cpcpInvSecond p) σ, i.e. ↑cu * cpcpInvSecond p = σ * ↑cu.
          let c : MulAut (CyclicGroup p × CyclicGroup p) := (cu : MulAut _)
          have hc_eq : σ = c * cpcpInvSecond p * c⁻¹ := by
            have h1 : c * cpcpInvSecond p = σ * c := hcu
            have h2 : c * cpcpInvSecond p * c⁻¹ = σ * c * c⁻¹ := by rw [h1]
            rw [h2, mul_inv_cancel_right]
          let conj_hom : CyclicGroup 2 →* MulAut (CyclicGroup p × CyclicGroup p) :=
            { toFun := fun x => c * canonicalC2OnCpCpAction_r1 p x * c⁻¹
              map_one' := by simp
              map_mul' := fun a b => by
                simp only [map_mul]; group }
          have h_eq_on_g₂ : φ_inter g₂ = conj_hom g₂ := by
            show σ = c * canonicalC2OnCpCpAction_r1 p g₂ * c⁻¹
            rw [h_r1_g₂]; exact hc_eq
          have h_eq : φ_inter = conj_hom :=
            monoidHom_eq_of_generator_eq hg₂_gen h_eq_on_g₂
          have h_action_eq : ∀ x : CyclicGroup 2,
              φ_inter x = c * canonicalC2OnCpCpAction_r1 p x * c⁻¹ :=
            fun x => congr_fun (congr_arg DFunLike.coe h_eq) x
          obtain ⟨e_iso⟩ := semidirectProduct_iso_of_conjugate_action
            (f_1 := canonicalC2OnCpCpAction_r1 p)
            (f_2 := φ_inter) c 1
            (fun x => by simpa using h_action_eq x)
          have : G ≃* SemidirectProduct (CyclicGroup p × CyclicGroup p) (CyclicGroup 2)
                       (canonicalC2OnCpCpAction_r1 p) :=
            h_iso_g_n_k.symm.trans (h_congr.trans e_iso.symm)
          tauto
        · -- σ is conjugate to cpcpInvBoth p, hence φ_inter ≅ canonicalC2OnCpCpAction_r2 p
          obtain ⟨cu, hcu⟩ := h_conj2
          let c : MulAut (CyclicGroup p × CyclicGroup p) := (cu : MulAut _)
          have hc_eq : σ = c * cpcpInvBoth p * c⁻¹ := by
            have h1 : c * cpcpInvBoth p = σ * c := hcu
            have h2 : c * cpcpInvBoth p * c⁻¹ = σ * c * c⁻¹ := by rw [h1]
            rw [h2, mul_inv_cancel_right]
          let conj_hom : CyclicGroup 2 →* MulAut (CyclicGroup p × CyclicGroup p) :=
            { toFun := fun x => c * canonicalC2OnCpCpAction_r2 p x * c⁻¹
              map_one' := by simp
              map_mul' := fun a b => by
                simp only [map_mul]; group }
          have h_eq_on_g₂ : φ_inter g₂ = conj_hom g₂ := by
            show σ = c * canonicalC2OnCpCpAction_r2 p g₂ * c⁻¹
            rw [h_r2_g₂]; exact hc_eq
          have h_eq : φ_inter = conj_hom :=
            monoidHom_eq_of_generator_eq hg₂_gen h_eq_on_g₂
          have h_action_eq : ∀ x : CyclicGroup 2,
              φ_inter x = c * canonicalC2OnCpCpAction_r2 p x * c⁻¹ :=
            fun x => congr_fun (congr_arg DFunLike.coe h_eq) x
          obtain ⟨e_iso⟩ := semidirectProduct_iso_of_conjugate_action
            (f_1 := canonicalC2OnCpCpAction_r2 p)
            (f_2 := φ_inter) c 1
            (fun x => by simpa using h_action_eq x)
          have : G ≃* SemidirectProduct (CyclicGroup p × CyclicGroup p) (CyclicGroup 2)
                       (canonicalC2OnCpCpAction_r2 p) :=
            h_iso_g_n_k.symm.trans (h_congr.trans e_iso.symm)
          tauto
  · -- n_2 = 1: Sylow 2-subgroup Q (order 2) is normal, complement K of order p²
    let Q : Sylow 2 G := default
    haveI : Subsingleton (Sylow 2 G) := (Nat.card_eq_one_iff_unique.mp h_n2_1).1
    have h_Q_card : Nat.card ↥(Q : Subgroup G) = 2 := by
      simpa using sylow_card_eq (Ne.symm hpne2) h_2_p2_card Q
    have h_Q_idx_p2 : ∀ Q : Sylow 2 G, (↑Q : Subgroup G).index = p ^ 2 := fun Q => by
      simpa using sylow_index_eq (Ne.symm hpne2) h_2_p2_card Q
    obtain ⟨K, hK⟩ := Subgroup.exists_right_complement'_of_coprime
      (N := (↑Q : Subgroup G)) (by
      rw [h_Q_card, h_Q_idx_p2]
      exact ((by norm_num : (2 : ℕ).Prime).coprime_of_ne h_p_prime.out
        (by omega : (2 : ℕ) ≠ p)).pow_right 2)
    have h_iso_g_q_k := SemidirectProduct.mulEquivSubgroup hK
    let φ : ↥K →* MulAut ↥(↑Q : Subgroup G) :=
      (↑Q : Subgroup G).normalizerMonoidHom.comp
        (Subgroup.inclusion (by simp [Subgroup.normalizer_eq_top]))
    have hK_card : Nat.card ↥K = p ^ 2 := by
      have h1 : Nat.card G = Nat.card ↥(↑Q : Subgroup G) * Nat.card ↥K := by
        have heq := Nat.card_congr h_iso_g_q_k.toEquiv
        rw [SemidirectProduct.card] at heq; exact heq.symm
      rw [h_Q_card, h] at h1
      exact (Nat.eq_of_mul_eq_mul_right (by norm_num : 0 < 2) (by linarith))
    have eQ : ↥(↑Q : Subgroup G) ≃* CyclicGroup 2 :=
      Classical.choice (prime_classification_of_group (n := 2) h_Q_card)
    -- Aut(C_2) is trivial since |Aut(C_2)| = 1
    have h_aut_card : Nat.card (MulAut ↥(↑Q : Subgroup G)) = 1 := by
      have h_iso_aut : MulAut ↥(↑Q : Subgroup G) ≃* MulAut (CyclicGroup 2) :=
        MulAut.congr eQ
      have h_aut_c2 : Nat.card (MulAut (CyclicGroup 2)) = 1 := by
        have := card_mulAut_cyclicGroup_prime (q := 2)
        simpa using this
      exact (Nat.card_congr h_iso_aut.toEquiv).trans h_aut_c2
    -- φ trivial since codomain has cardinality 1
    have h_phi_triv : φ = 1 := eq_one_of_coprime_card (by
      rw [hK_card, h_aut_card]; simp)
    have h_2p2cop : Nat.Coprime 2 (p ^ 2) := h2cop.pow_right 2
    have h_p22cop : Nat.Coprime (p ^ 2) 2 := h_2p2cop.symm
    rcases (p_squared_classification (p := p) hK_card) with h_K_Cp2 | h_K_CpCp
    · -- K ≅ C_{p²}: G ≅ C_2 × C_{p²} ≅ C_{2p²}
      let eK := h_K_Cp2.some
      have : G ≃* CyclicGroup (2 * p ^ 2) := h_iso_g_q_k.symm.trans
        ((SemidirectProduct.mulEquivOfTrivialAction h_phi_triv).trans
          ((eQ.prodCongr eK).trans (CyclicGroup.prodMulEquiv h_2p2cop)))
      tauto
    · -- K ≅ C_p × C_p: G ≅ C_2 × (C_p × C_p) ≅ C_p × C_p × C_2
      let eK := h_K_CpCp.some
      have : G ≃* CyclicGroup p × CyclicGroup p × CyclicGroup 2 := h_iso_g_q_k.symm.trans
        ((SemidirectProduct.mulEquivOfTrivialAction h_phi_triv).trans
          ((eQ.prodCongr eK).trans (MulEquiv.prodComm.trans MulEquiv.prodAssoc)))
      tauto
