import Mathlib
import «M2rGroup7».Lemmas.SylowUtils
import «M2rGroup7».Lemmas.LinearAlgebraUtils
import «M2rGroup7».Lemmas.GroupTheoryLemmas
import «M2rGroup7».Lemmas.ClassificationUtils
import «M2rGroup7».Lemmas.HomomorphismUtils
import «M2rGroup7».Lemmas.NumberTheoryUtils
import «M2rGroup7».P2qClassification.CycPGroupClassification

/-- Canonical nontrivial action `C_2 →* Aut(C_{p^2})`, image of order 2. -/
def canonicalC2OnCp2Action {p : ℕ} [h_p_prime : Fact p.Prime] (h_p_ne_2 : p ≠ 2) :
    CyclicGroup 2 →* MulAut (CyclicGroup (p ^ 2)) :=
  haveI := h_p_prime
  haveI : Fact (Nat.Prime 2) := ⟨by norm_num⟩
  haveI : NeZero (p ^ 2) := ⟨pow_ne_zero 2 h_p_prime.out.ne_zero⟩
  haveI : NeZero (2 : ℕ) := ⟨by norm_num⟩
  haveI : NeZero ((2:ℕ) ^ 1) := ⟨pow_ne_zero 1 (by norm_num)⟩
  transportCpCqHom (pow_one 2) (rfl : p ^ 2 = p ^ 2)
    (canonicalAction 2 p 2 1 (Ne.symm h_p_ne_2) h_p_ne_2 (by norm_num)
       1 (by
          have h := (Nat.le_min.mp (one_le_min_two_factorization_two h_p_ne_2)).2
          exact Nat.le_min.mpr ⟨le_refl 1, h⟩))

/-! ## Canonical actions on `C_p × C_p` for the `C_2` factor.

We build two elementary automorphisms of `C_p × C_p`: inversion on the second
coordinate (`cpcpInvSecond`) and inversion on both coordinates (`cpcpInvBoth`).
Both have order dividing 2; we turn them into actions `C_2 →* MulAut (C_p × C_p)`
via `cyclicHom`. -/

/-- Inversion on the second coordinate of `C_p × C_p`. -/
def cpcpInvSecond (p : ℕ) [NeZero p] : MulAut (CyclicGroup p × CyclicGroup p) where
  toFun x := (x.1, x.2⁻¹)
  invFun x := (x.1, x.2⁻¹)
  left_inv := by rintro ⟨a, b⟩; simp
  right_inv := by rintro ⟨a, b⟩; simp
  map_mul' := by
    rintro ⟨a₁, b₁⟩ ⟨a₂, b₂⟩
    refine Prod.ext rfl ?_
    change (b₁ * b₂)⁻¹ = b₁⁻¹ * b₂⁻¹
    rw [mul_inv]

/-- Inversion on both coordinates of `C_p × C_p`. -/
def cpcpInvBoth (p : ℕ) [NeZero p] : MulAut (CyclicGroup p × CyclicGroup p) where
  toFun x := (x.1⁻¹, x.2⁻¹)
  invFun x := (x.1⁻¹, x.2⁻¹)
  left_inv := by rintro ⟨a, b⟩; simp
  right_inv := by rintro ⟨a, b⟩; simp
  map_mul' := by
    rintro ⟨a₁, b₁⟩ ⟨a₂, b₂⟩
    refine Prod.ext ?_ ?_
    · change (a₁ * a₂)⁻¹ = a₁⁻¹ * a₂⁻¹; rw [mul_inv]
    · change (b₁ * b₂)⁻¹ = b₁⁻¹ * b₂⁻¹; rw [mul_inv]

lemma cpcpInvSecond_sq (p : ℕ) [NeZero p] : (cpcpInvSecond p) ^ 2 = 1 := by
  ext x
  · rw [sq, MulAut.mul_apply, MulAut.one_apply]
    change ((x.1, x.2⁻¹).1, (x.1, x.2⁻¹).2⁻¹).1 = x.1
    simp
  · rw [sq, MulAut.mul_apply, MulAut.one_apply]
    change ((x.1, x.2⁻¹).1, (x.1, x.2⁻¹).2⁻¹).2 = x.2
    simp

lemma cpcpInvBoth_sq (p : ℕ) [NeZero p] : (cpcpInvBoth p) ^ 2 = 1 := by
  ext x
  · rw [sq, MulAut.mul_apply, MulAut.one_apply]
    change ((x.1⁻¹, x.2⁻¹).1⁻¹, (x.1⁻¹, x.2⁻¹).2⁻¹).1 = x.1
    simp
  · rw [sq, MulAut.mul_apply, MulAut.one_apply]
    change ((x.1⁻¹, x.2⁻¹).1⁻¹, (x.1⁻¹, x.2⁻¹).2⁻¹).2 = x.2
    simp

/-- Canonical action `C_2 →* Aut(C_p × C_p)` with image generated by inversion on the
second coordinate. -/
def canonicalC2OnCpCpAction_r1 (p : ℕ) [NeZero p] :
    CyclicGroup 2 →* MulAut (CyclicGroup p × CyclicGroup p) :=
  cyclicHom 2 (cpcpInvSecond p) (cpcpInvSecond_sq p)

/-- Canonical action `C_2 →* Aut(C_p × C_p)` with image generated by inversion on both
coordinates (the "minus identity" action). -/
def canonicalC2OnCpCpAction_r2 (p : ℕ) [NeZero p] :
    CyclicGroup 2 →* MulAut (CyclicGroup p × CyclicGroup p) :=
  cyclicHom 2 (cpcpInvBoth p) (cpcpInvBoth_sq p)

/-! ## Conjugacy classification of order-two elements of `MulAut(C_p × C_p)`.

For `p` an odd prime, every order-two element of `MulAut(C_p × C_p)` is conjugate
in `MulAut(C_p × C_p)` to either `cpcpInvSecond p` or `cpcpInvBoth p`. -/

/-- For an odd prime `p`, every order-two element `σ` of `MulAut(C_p × C_p)` is
conjugate to one of the two canonical inversion automorphisms `cpcpInvSecond p` or
`cpcpInvBoth p`.

The proof strategy is to view `Additive (C_p × C_p)` as a 2-dimensional `F_p`-vector
space and analyse the ±1 eigenspaces of the linear automorphism corresponding to `σ`.
Either both `+1` and `-1` eigenspaces are 1-dimensional (giving the `cpcpInvSecond`
case via a change-of-basis), or `σ` acts as `-id` (giving the `cpcpInvBoth` case
directly). -/
lemma mulAut_cpcp_order_two_conj {p : ℕ} [hp : Fact p.Prime] (hp_ne_2 : p ≠ 2)
    (σ : MulAut (CyclicGroup p × CyclicGroup p)) (hσ : orderOf σ = 2) :
    IsConj (cpcpInvSecond p) σ ∨ IsConj (cpcpInvBoth p) σ := by
  -- BLOCKING: detailed linear-algebra proof. The argument is as outlined above; this
  -- is the substantive content of the C_p × C_p case for `classification_2p2`.
  sorry

/-! ## Range cards for the new canonical actions. -/

/-- The order of `cpcpInvSecond p` is exactly 2 (provided p ≠ 2). -/
lemma orderOf_cpcpInvSecond {p : ℕ} [hp : Fact p.Prime] (hp_ne_2 : p ≠ 2) :
    orderOf (cpcpInvSecond p) = 2 := by
  haveI : NeZero p := ⟨hp.out.pos.ne'⟩
  refine orderOf_eq_prime (cpcpInvSecond_sq p) ?_
  intro h
  -- (cpcpInvSecond p) = 1 ⇒ on the pair (1, ofAdd 1), second coord inverts to itself.
  have h_app := congr_fun (congr_arg DFunLike.coe h)
    ((1 : CyclicGroup p), (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p))
  have h_eq : ((1 : CyclicGroup p), (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)⁻¹) =
      ((1 : CyclicGroup p), (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)) := h_app
  have h_inv : (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)⁻¹ =
      (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p) :=
    (Prod.mk.injEq _ _ _ _).mp h_eq |>.2
  -- This gives 1 = -1 in ZMod p, hence p ∣ 2, hence p = 2.
  have h_zmod_eq : (-1 : ZMod p) = (1 : ZMod p) := by
    have : (Multiplicative.ofAdd (-(1 : ZMod p)) : CyclicGroup p) =
        (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p) := by
      rw [show (Multiplicative.ofAdd (-(1 : ZMod p)) : CyclicGroup p) =
        (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)⁻¹ from rfl]
      exact h_inv
    exact (Multiplicative.ofAdd.injective this)
  -- (-1 : ZMod p) = 1 means 2 ≡ 0 (mod p), hence p ∣ 2, hence p = 2.
  have h_two_zero : (2 : ZMod p) = 0 := by linear_combination -h_zmod_eq
  -- p ∣ 2 because (2 : ZMod p) = 0
  have h_two_cast : ((2 : ℕ) : ZMod p) = 0 := by exact_mod_cast h_two_zero
  have h_p_dvd : p ∣ 2 := (ZMod.natCast_eq_zero_iff 2 p).mp h_two_cast
  have h_p_eq : p = 2 :=
    (Nat.prime_dvd_prime_iff_eq hp.out Nat.prime_two).mp h_p_dvd
  exact hp_ne_2 h_p_eq

/-- The order of `cpcpInvBoth p` is exactly 2 (provided p ≠ 2). -/
lemma orderOf_cpcpInvBoth {p : ℕ} [hp : Fact p.Prime] (hp_ne_2 : p ≠ 2) :
    orderOf (cpcpInvBoth p) = 2 := by
  haveI : NeZero p := ⟨hp.out.pos.ne'⟩
  refine orderOf_eq_prime (cpcpInvBoth_sq p) ?_
  intro h
  have h_app := congr_fun (congr_arg DFunLike.coe h)
    ((Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p), (1 : CyclicGroup p))
  have h_eq : ((Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)⁻¹,
      (1 : CyclicGroup p)⁻¹) =
      ((Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p), (1 : CyclicGroup p)) := h_app
  have h_inv : (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)⁻¹ =
      (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p) :=
    (Prod.mk.injEq _ _ _ _).mp h_eq |>.1
  have h_zmod_eq : (-1 : ZMod p) = (1 : ZMod p) := by
    have : (Multiplicative.ofAdd (-(1 : ZMod p)) : CyclicGroup p) =
        (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p) := by
      rw [show (Multiplicative.ofAdd (-(1 : ZMod p)) : CyclicGroup p) =
        (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)⁻¹ from rfl]
      exact h_inv
    exact (Multiplicative.ofAdd.injective this)
  have h_two_zero : (2 : ZMod p) = 0 := by linear_combination -h_zmod_eq
  have h_two_cast : ((2 : ℕ) : ZMod p) = 0 := by exact_mod_cast h_two_zero
  have h_p_dvd : p ∣ 2 := (ZMod.natCast_eq_zero_iff 2 p).mp h_two_cast
  exact hp_ne_2 ((Nat.prime_dvd_prime_iff_eq hp.out Nat.prime_two).mp h_p_dvd)

lemma canonicalC2OnCpCpAction_r1_range_card {p : ℕ} [hp : Fact p.Prime] (hp_ne_2 : p ≠ 2) :
    Nat.card (canonicalC2OnCpCpAction_r1 p).range = 2 := by
  haveI : NeZero p := ⟨hp.out.pos.ne'⟩
  show Nat.card (cyclicHom 2 (cpcpInvSecond p) (cpcpInvSecond_sq p)).range = 2
  rw [cyclicHom_range, Nat.card_zpowers, orderOf_cpcpInvSecond hp_ne_2]

lemma canonicalC2OnCpCpAction_r2_range_card {p : ℕ} [hp : Fact p.Prime] (hp_ne_2 : p ≠ 2) :
    Nat.card (canonicalC2OnCpCpAction_r2 p).range = 2 := by
  haveI : NeZero p := ⟨hp.out.pos.ne'⟩
  show Nat.card (cyclicHom 2 (cpcpInvBoth p) (cpcpInvBoth_sq p)).range = 2
  rw [cyclicHom_range, Nat.card_zpowers, orderOf_cpcpInvBoth hp_ne_2]

/-! ## Main classification of groups of order `2p^2`. -/

set_option maxHeartbeats 400000 in
theorem classification_2p2 {p : ℕ} [h_p_prime : Fact p.Prime] [Group G]
    (h_ge_3 : p ≥ 3) (h : Nat.card G = p ^ 2 * 2)
    : Nonempty (G ≃* CyclicGroup (2 * p ^ 2))
      ∨ Nonempty (G ≃* CyclicGroup p × CyclicGroup p × CyclicGroup 2)
      ∨ Nonempty (G ≃* SemidirectProduct (CyclicGroup (p ^ 2)) (CyclicGroup 2)
                         (canonicalC2OnCp2Action (by omega : p ≠ 2)))
      ∨ Nonempty (G ≃* SemidirectProduct (CyclicGroup p × CyclicGroup p) (CyclicGroup 2)
                         (canonicalC2OnCpCpAction_r1 p))
      ∨ Nonempty (G ≃* SemidirectProduct (CyclicGroup p × CyclicGroup p) (CyclicGroup 2)
                         (canonicalC2OnCpCpAction_r2 p)) := by
  sorry
