import Mathlib
import «M2rGroup7».Lemmas.SylowUtils
import «M2rGroup7».Lemmas.LinearAlgebraUtils
import «M2rGroup7».Lemmas.GroupTheoryLemmas
import «M2rGroup7».Lemmas.ClassificationUtils
import «M2rGroup7».Lemmas.HomomorphismUtils
import «M2rGroup7».Lemmas.NumberTheoryUtils
import «M2rGroup7».P2qClassification.CycPGroupClassification

/-- Canonical nontrivial action `C_2 →* Aut(C_{p^2})`, image of order 2. -/
def canonicalC2OnCp2Action {p : ℕ} [h_p_prime : Fact p.Prime] (h_p_ne_2 : p ≠ 2) :
    CyclicGroup 2 →* MulAut (CyclicGroup (p ^ 2)) :=
  haveI := h_p_prime
  haveI : Fact (Nat.Prime 2) := ⟨by norm_num⟩
  haveI : NeZero (p ^ 2) := ⟨pow_ne_zero 2 h_p_prime.out.ne_zero⟩
  haveI : NeZero (2 : ℕ) := ⟨by norm_num⟩
  haveI : NeZero ((2:ℕ) ^ 1) := ⟨pow_ne_zero 1 (by norm_num)⟩
  transportCpCqHom (pow_one 2) (rfl : p ^ 2 = p ^ 2)
    (canonicalAction 2 p 2 1 (Ne.symm h_p_ne_2) h_p_ne_2 (by norm_num)
       1 (by
          have h := (Nat.le_min.mp (one_le_min_two_factorization_two h_p_ne_2)).2
          exact Nat.le_min.mpr ⟨le_refl 1, h⟩))

/-! ## Canonical actions on `C_p × C_p` for the `C_2` factor.

We build two elementary automorphisms of `C_p × C_p`: inversion on the second
coordinate (`cpcpInvSecond`) and inversion on both coordinates (`cpcpInvBoth`).
Both have order dividing 2; we turn them into actions `C_2 →* MulAut (C_p × C_p)`
via `cyclicHom`. -/

/-- Inversion on the second coordinate of `C_p × C_p`. -/
def cpcpInvSecond (p : ℕ) [NeZero p] : MulAut (CyclicGroup p × CyclicGroup p) where
  toFun x := (x.1, x.2⁻¹)
  invFun x := (x.1, x.2⁻¹)
  left_inv := by rintro ⟨a, b⟩; simp
  right_inv := by rintro ⟨a, b⟩; simp
  map_mul' := by
    rintro ⟨a₁, b₁⟩ ⟨a₂, b₂⟩
    refine Prod.ext rfl ?_
    change (b₁ * b₂)⁻¹ = b₁⁻¹ * b₂⁻¹
    rw [mul_inv]

/-- Inversion on both coordinates of `C_p × C_p`. -/
def cpcpInvBoth (p : ℕ) [NeZero p] : MulAut (CyclicGroup p × CyclicGroup p) where
  toFun x := (x.1⁻¹, x.2⁻¹)
  invFun x := (x.1⁻¹, x.2⁻¹)
  left_inv := by rintro ⟨a, b⟩; simp
  right_inv := by rintro ⟨a, b⟩; simp
  map_mul' := by
    rintro ⟨a₁, b₁⟩ ⟨a₂, b₂⟩
    refine Prod.ext ?_ ?_
    · change (a₁ * a₂)⁻¹ = a₁⁻¹ * a₂⁻¹; rw [mul_inv]
    · change (b₁ * b₂)⁻¹ = b₁⁻¹ * b₂⁻¹; rw [mul_inv]

lemma cpcpInvSecond_sq (p : ℕ) [NeZero p] : (cpcpInvSecond p) ^ 2 = 1 := by
  ext x
  · rw [sq, MulAut.mul_apply, MulAut.one_apply]
    change ((x.1, x.2⁻¹).1, (x.1, x.2⁻¹).2⁻¹).1 = x.1
    simp
  · rw [sq, MulAut.mul_apply, MulAut.one_apply]
    change ((x.1, x.2⁻¹).1, (x.1, x.2⁻¹).2⁻¹).2 = x.2
    simp

lemma cpcpInvBoth_sq (p : ℕ) [NeZero p] : (cpcpInvBoth p) ^ 2 = 1 := by
  ext x
  · rw [sq, MulAut.mul_apply, MulAut.one_apply]
    change ((x.1⁻¹, x.2⁻¹).1⁻¹, (x.1⁻¹, x.2⁻¹).2⁻¹).1 = x.1
    simp
  · rw [sq, MulAut.mul_apply, MulAut.one_apply]
    change ((x.1⁻¹, x.2⁻¹).1⁻¹, (x.1⁻¹, x.2⁻¹).2⁻¹).2 = x.2
    simp

/-- Canonical action `C_2 →* Aut(C_p × C_p)` with image generated by inversion on the
second coordinate. -/
def canonicalC2OnCpCpAction_r1 (p : ℕ) [NeZero p] :
    CyclicGroup 2 →* MulAut (CyclicGroup p × CyclicGroup p) :=
  cyclicHom 2 (cpcpInvSecond p) (cpcpInvSecond_sq p)

/-- Canonical action `C_2 →* Aut(C_p × C_p)` with image generated by inversion on both
coordinates (the "minus identity" action). -/
def canonicalC2OnCpCpAction_r2 (p : ℕ) [NeZero p] :
    CyclicGroup 2 →* MulAut (CyclicGroup p × CyclicGroup p) :=
  cyclicHom 2 (cpcpInvBoth p) (cpcpInvBoth_sq p)

/-! ## Conjugacy classification of order-two elements of `MulAut(C_p × C_p)`.

For `p` an odd prime, every order-two element of `MulAut(C_p × C_p)` is conjugate
in `MulAut(C_p × C_p)` to either `cpcpInvSecond p` or `cpcpInvBoth p`. -/

/-- For an odd prime `p`, every order-two element `σ` of `MulAut(C_p × C_p)` is
conjugate to one of the two canonical inversion automorphisms `cpcpInvSecond p` or
`cpcpInvBoth p`.

The proof strategy is to view `Additive (C_p × C_p)` as a 2-dimensional `F_p`-vector
space and analyse the ±1 eigenspaces of the linear automorphism corresponding to `σ`.
Either both `+1` and `-1` eigenspaces are 1-dimensional (giving the `cpcpInvSecond`
case via a change-of-basis), or `σ` acts as `-id` (giving the `cpcpInvBoth` case
directly). -/
lemma mulAut_cpcp_order_two_conj {p : ℕ} [hp : Fact p.Prime] (hp_ne_2 : p ≠ 2)
    (σ : MulAut (CyclicGroup p × CyclicGroup p)) (hσ : orderOf σ = 2) :
    IsConj (cpcpInvSecond p) σ ∨ IsConj (cpcpInvBoth p) σ := by
  -- BLOCKING: detailed linear-algebra proof. The argument is as outlined above; this
  -- is the substantive content of the C_p × C_p case for `classification_2p2`.
  sorry

/-! ## Range cards for the new canonical actions. -/

/-- The order of `cpcpInvSecond p` is exactly 2 (provided p ≠ 2). -/
lemma orderOf_cpcpInvSecond {p : ℕ} [hp : Fact p.Prime] (hp_ne_2 : p ≠ 2) :
    orderOf (cpcpInvSecond p) = 2 := by
  haveI : NeZero p := ⟨hp.out.pos.ne'⟩
  refine orderOf_eq_prime (cpcpInvSecond_sq p) ?_
  intro h
  -- (cpcpInvSecond p) = 1 ⇒ on the pair (1, ofAdd 1), second coord inverts to itself.
  have h_app := congr_fun (congr_arg DFunLike.coe h)
    ((1 : CyclicGroup p), (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p))
  have h_eq : ((1 : CyclicGroup p), (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)⁻¹) =
      ((1 : CyclicGroup p), (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)) := h_app
  have h_inv : (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)⁻¹ =
      (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p) :=
    (Prod.mk.injEq _ _ _ _).mp h_eq |>.2
  -- This gives 1 = -1 in ZMod p, hence p ∣ 2, hence p = 2.
  have h_zmod_eq : (-1 : ZMod p) = (1 : ZMod p) := by
    have : (Multiplicative.ofAdd (-(1 : ZMod p)) : CyclicGroup p) =
        (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p) := by
      rw [show (Multiplicative.ofAdd (-(1 : ZMod p)) : CyclicGroup p) =
        (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)⁻¹ from rfl]
      exact h_inv
    exact (Multiplicative.ofAdd.injective this)
  -- (-1 : ZMod p) = 1 means 2 ≡ 0 (mod p), hence p ∣ 2, hence p = 2.
  have h_two_zero : (2 : ZMod p) = 0 := by linear_combination -h_zmod_eq
  -- p ∣ 2 because (2 : ZMod p) = 0
  have h_two_cast : ((2 : ℕ) : ZMod p) = 0 := by exact_mod_cast h_two_zero
  have h_p_dvd : p ∣ 2 := (ZMod.natCast_eq_zero_iff 2 p).mp h_two_cast
  have h_p_eq : p = 2 :=
    (Nat.prime_dvd_prime_iff_eq hp.out Nat.prime_two).mp h_p_dvd
  exact hp_ne_2 h_p_eq

/-- The order of `cpcpInvBoth p` is exactly 2 (provided p ≠ 2). -/
lemma orderOf_cpcpInvBoth {p : ℕ} [hp : Fact p.Prime] (hp_ne_2 : p ≠ 2) :
    orderOf (cpcpInvBoth p) = 2 := by
  haveI : NeZero p := ⟨hp.out.pos.ne'⟩
  refine orderOf_eq_prime (cpcpInvBoth_sq p) ?_
  intro h
  have h_app := congr_fun (congr_arg DFunLike.coe h)
    ((Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p), (1 : CyclicGroup p))
  have h_eq : ((Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)⁻¹,
      (1 : CyclicGroup p)⁻¹) =
      ((Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p), (1 : CyclicGroup p)) := h_app
  have h_inv : (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)⁻¹ =
      (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p) :=
    (Prod.mk.injEq _ _ _ _).mp h_eq |>.1
  have h_zmod_eq : (-1 : ZMod p) = (1 : ZMod p) := by
    have : (Multiplicative.ofAdd (-(1 : ZMod p)) : CyclicGroup p) =
        (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p) := by
      rw [show (Multiplicative.ofAdd (-(1 : ZMod p)) : CyclicGroup p) =
        (Multiplicative.ofAdd (1 : ZMod p) : CyclicGroup p)⁻¹ from rfl]
      exact h_inv
    exact (Multiplicative.ofAdd.injective this)
  have h_two_zero : (2 : ZMod p) = 0 := by linear_combination -h_zmod_eq
  have h_two_cast : ((2 : ℕ) : ZMod p) = 0 := by exact_mod_cast h_two_zero
  have h_p_dvd : p ∣ 2 := (ZMod.natCast_eq_zero_iff 2 p).mp h_two_cast
  exact hp_ne_2 ((Nat.prime_dvd_prime_iff_eq hp.out Nat.prime_two).mp h_p_dvd)

lemma canonicalC2OnCpCpAction_r1_range_card {p : ℕ} [hp : Fact p.Prime] (hp_ne_2 : p ≠ 2) :
    Nat.card (canonicalC2OnCpCpAction_r1 p).range = 2 := by
  haveI : NeZero p := ⟨hp.out.pos.ne'⟩
  show Nat.card (cyclicHom 2 (cpcpInvSecond p) (cpcpInvSecond_sq p)).range = 2
  rw [cyclicHom_range, Nat.card_zpowers, orderOf_cpcpInvSecond hp_ne_2]

lemma canonicalC2OnCpCpAction_r2_range_card {p : ℕ} [hp : Fact p.Prime] (hp_ne_2 : p ≠ 2) :
    Nat.card (canonicalC2OnCpCpAction_r2 p).range = 2 := by
  haveI : NeZero p := ⟨hp.out.pos.ne'⟩
  show Nat.card (cyclicHom 2 (cpcpInvBoth p) (cpcpInvBoth_sq p)).range = 2
  rw [cyclicHom_range, Nat.card_zpowers, orderOf_cpcpInvBoth hp_ne_2]

/-! ## Main classification of groups of order `2p^2`. -/

set_option maxHeartbeats 400000 in
theorem classification_2p2 {p : ℕ} [h_p_prime : Fact p.Prime] [Group G]
    (h_ge_3 : p ≥ 3) (h : Nat.card G = p ^ 2 * 2)
    : Nonempty (G ≃* CyclicGroup (2 * p ^ 2))
      ∨ Nonempty (G ≃* CyclicGroup p × CyclicGroup p × CyclicGroup 2)
      ∨ Nonempty (G ≃* SemidirectProduct (CyclicGroup (p ^ 2)) (CyclicGroup 2)
                         (canonicalC2OnCp2Action (by omega : p ≠ 2)))
      ∨ Nonempty (G ≃* SemidirectProduct (CyclicGroup p × CyclicGroup p) (CyclicGroup 2)
                         (canonicalC2OnCpCpAction_r1 p))
      ∨ Nonempty (G ≃* SemidirectProduct (CyclicGroup p × CyclicGroup p) (CyclicGroup 2)
                         (canonicalC2OnCpCpAction_r2 p)) := by
  haveI : NeZero p := ⟨h_p_prime.out.ne_zero⟩
  haveI : Fact (Nat.Prime 2) := ⟨by norm_num⟩
  have hp_ne_2 : p ≠ 2 := by omega
  haveI : Finite G := by
    apply Nat.finite_of_card_ne_zero; rw [h]
    have p_ne : p ≠ 0 := Nat.Prime.ne_zero h_p_prime.elim
    simp; tauto
  let n_p := Nat.card (Sylow p G)
  let n_2 := Nat.card (Sylow 2 G)
  have hpne2 : p ≠ 2 := hp_ne_2
  have n_p_or_n_2_one : n_p = 1 ∨ n_2 = 1 :=
    p2q_group_has_normal_sylow_subgroup G hpne2 h
  have h2cop : Nat.Coprime 2 p :=
    ((by norm_num : (2 : ℕ).Prime).coprime_of_ne h_p_prime.out (by omega))
  have h_p2_p_card : Nat.card G = p ^ 2 * 2 ^ 1 := by simpa using h
  have h_2_p2_card : Nat.card G = 2 ^ 1 * p ^ 2 := by rw [h]; ring
  rcases n_p_or_n_2_one with h_np_1 | h_n2_1
  · -- n_p = 1: Sylow p-subgroup N (order p²) is normal, complement K of order 2
    let N : Sylow p G := default
    haveI : Subsingleton (Sylow p G) := (Nat.card_eq_one_iff_unique.mp h_np_1).1
    have h_N_card : Nat.card ↥(N : Subgroup G) = p ^ 2 :=
      sylow_card_eq hpne2 h_p2_p_card N
    have h_N_idx_2 : ∀ N : Sylow p G, (↑N : Subgroup G).index = 2 := fun N => by
      simpa using sylow_index_eq hpne2 h_p2_p_card N
    obtain ⟨K, hK⟩ := Subgroup.exists_right_complement'_of_coprime
      (N := (↑N : Subgroup G)) (by
      rw [h_N_card, h_N_idx_2]
      exact ((h_p_prime.out.coprime_of_ne (by norm_num : (2 : ℕ).Prime) hpne2)).pow_left 2)
    have h_iso_g_n_k := SemidirectProduct.mulEquivSubgroup hK
    let φ : ↥K →* MulAut ↥(↑N : Subgroup G) :=
      (↑N : Subgroup G).normalizerMonoidHom.comp
        (Subgroup.inclusion (by simp [Subgroup.normalizer_eq_top]))
    have hK_card : Nat.card ↥K = 2 := by
      have h1 : Nat.card G = Nat.card ↥(↑N : Subgroup G) * Nat.card ↥K := by
        have heq := Nat.card_congr h_iso_g_n_k.toEquiv
        rw [SemidirectProduct.card] at heq; exact heq.symm
      rw [h_N_card, h] at h1
      have hp_pos : 0 < p ^ 2 := pow_pos h_p_prime.out.pos 2
      exact (Nat.eq_of_mul_eq_mul_left hp_pos h1).symm
    have eK : ↥K ≃* CyclicGroup 2 :=
      Classical.choice (prime_classification_of_group (n := 2) hK_card)
    have h2p2cop : Nat.Coprime 2 (p ^ 2) := h2cop.pow_right 2
    have hp2_2cop : Nat.Coprime (p ^ 2) 2 := h2p2cop.symm
    rcases (p_squared_classification (p := p) h_N_card) with h_N_Cp2 | h_N_CpCp
    · -- N ≅ C_{p²}: bridge φ via eN, eK, dispatch via classify_Cqn_rtimes_Cpm
      let eN := h_N_Cp2.some
      let φ_inter : CyclicGroup 2 →* MulAut (CyclicGroup (p ^ 2)) :=
        (MulAut.congr eN).toMonoidHom.comp (φ.comp eK.symm.toMonoidHom)
      have h_congr : ↥(↑N : Subgroup G) ⋊[φ] ↥K ≃*
          SemidirectProduct (CyclicGroup (p ^ 2)) (CyclicGroup 2) φ_inter :=
        SemidirectProduct.congr' (φ₁ := φ) (fn := eN) (fg := eK)
      haveI : NeZero (p ^ 2) := ⟨pow_ne_zero 2 h_p_prime.out.ne_zero⟩
      haveI : NeZero ((2:ℕ)^1) := ⟨pow_ne_zero 1 (by norm_num)⟩
      have h2p : (2 : ℕ) ≠ p := by omega
      have h21 : ((2:ℕ)^1 : ℕ) = 2 := by norm_num
      have hp22 : (p^2 : ℕ) = p^2 := rfl
      have h_pre_iso := SemidirectProduct.transportCpCqIso h21.symm hp22.symm φ_inter
      obtain ⟨⟨r, hr_lt⟩, ⟨e_pre⟩, _⟩ := classify_Cqn_rtimes_Cpm (p := 2) (q := p) h2p hpne2 1 2
        Nat.one_pos (by norm_num)
        (transportCpCqHom h21.symm hp22.symm φ_inter)
      have hr_le : r ≤ min 1 ((p - 1).factorization 2) := Nat.lt_succ_iff.mp hr_lt
      let canonR := fun r (hr : r ≤ min 1 ((p - 1).factorization 2)) =>
        canonicalAction 2 p 2 1 h2p hpne2 (by norm_num) r hr
      let e_back := fun r hr => SemidirectProduct.transportCpCqIso h21 hp22 (canonR r hr)
      let pre := h_iso_g_n_k.symm.trans (h_congr.trans (h_pre_iso.trans
        (e_pre.trans (e_back r hr_le))))
      have hr_le_1 : r ≤ 1 := hr_le.trans (min_le_left _ _)
      interval_cases r
      · -- r = 0: trivial action → G ≃* C_{2p²}
        have h_triv := eq_one_of_range_card_one (by
          show Nat.card (transportCpCqHom h21 hp22 (canonR 0 hr_le)).range = 1
          rw [transportCpCqHom_range_card]
          simpa using canonicalAction_range_card 2 p 2 1 0 h2p hpne2 (by norm_num) hr_le)
        have : G ≃* CyclicGroup (2 * p ^ 2) := pre.trans
          ((SemidirectProduct.mulEquivOfTrivialAction h_triv).trans
            (MulEquiv.prodComm.trans (CyclicGroup.prodMulEquiv h2p2cop)))
        tauto
      · -- r = 1: matches `canonicalC2OnCp2Action`.
        tauto
    · -- N ≅ C_p × C_p: by_cases on φ_inter triviality
      let eN := h_N_CpCp.some
      let φ_inter : CyclicGroup 2 →* MulAut (CyclicGroup p × CyclicGroup p) :=
        (MulAut.congr eN).toMonoidHom.comp (φ.comp eK.symm.toMonoidHom)
      have h_congr : ↥(↑N : Subgroup G) ⋊[φ] ↥K ≃*
          SemidirectProduct (CyclicGroup p × CyclicGroup p) (CyclicGroup 2) φ_inter :=
        SemidirectProduct.congr' (φ₁ := φ) (fn := eN) (fg := eK)
      by_cases h_triv : φ_inter = 1
      · -- φ_inter trivial → G ≃* (C_p × C_p) × C_2
        have : G ≃* CyclicGroup p × CyclicGroup p × CyclicGroup 2 :=
          h_iso_g_n_k.symm.trans (h_congr.trans
            ((SemidirectProduct.mulEquivOfTrivialAction h_triv).trans
              MulEquiv.prodAssoc))
        tauto
      · -- φ_inter nontrivial: image has order 2 by Lagrange (|C_2| = 2 prime)
        -- so φ_inter is determined by a single order-2 σ; conjugate to canon₁ or canon₂.
        -- φ_inter(generator) has order dividing 2; nontriviality forces it to be 2.
        have h_card_K2 : Nat.card (CyclicGroup 2) = 2 := card_cyclicGroup 2
        -- |φ_inter.range| divides |C_2| = 2, and isn't 1.
        have h_range_dvd : Nat.card φ_inter.range ∣ 2 := by
          have := Subgroup.card_range_dvd φ_inter; rwa [h_card_K2] at this
        have h_range_ne_1 : Nat.card φ_inter.range ≠ 1 :=
          fun h => h_triv (eq_one_of_range_card_one h)
        have h_range_card : Nat.card φ_inter.range = 2 := by
          rcases (Nat.dvd_prime Nat.prime_two).mp h_range_dvd with h1 | h2
          · exact absurd h1 h_range_ne_1
          · exact h2
        -- the generator (Multiplicative.ofAdd 1 : CyclicGroup 2) maps to some σ
        let g₂ : CyclicGroup 2 := Multiplicative.ofAdd (1 : ZMod 2)
        let σ : MulAut (CyclicGroup p × CyclicGroup p) := φ_inter g₂
        have hg2_sq : g₂ ^ 2 = 1 := by
          have h := pow_card_eq_one' (G := CyclicGroup 2) (x := g₂)
          rwa [card_cyclicGroup] at h
        have hσ_sq : σ ^ 2 = 1 := by
          have := congr_arg φ_inter hg2_sq
          rwa [map_pow, map_one] at this
        -- σ ≠ 1: otherwise φ_inter would be trivial since g₂ generates.
        have hg₂_gen : ∀ x : CyclicGroup 2, x ∈ Subgroup.zpowers g₂ := by
          intro x
          refine Subgroup.mem_zpowers_iff.mpr ⟨((Multiplicative.toAdd x).val : ℤ), ?_⟩
          show Multiplicative.ofAdd (1 : ZMod 2) ^ ((Multiplicative.toAdd x).val : ℤ) = x
          rw [← Multiplicative.ofAdd.apply_symm_apply x]
          show Multiplicative.ofAdd (1 : ZMod 2) ^ ((Multiplicative.toAdd x).val : ℤ)
              = Multiplicative.ofAdd (Multiplicative.toAdd x)
          rw [← ofAdd_zsmul, zsmul_one]
          congr 1
          push_cast
          exact ZMod.natCast_zmod_val _
        have hσ_ne_one : σ ≠ 1 := by
          intro hσ1
          apply h_triv
          have hext : ∀ x : CyclicGroup 2, φ_inter x = 1 := by
            intro x
            obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp (hg₂_gen x)
            have : φ_inter x = (φ_inter g₂) ^ n := by rw [← hn, map_zpow]
            rw [this, show φ_inter g₂ = σ from rfl, hσ1, one_zpow]
          ext x : 1; rw [hext x]; rfl
        have hσ_order : orderOf σ = 2 := orderOf_eq_prime hσ_sq hσ_ne_one
        -- Apply mulAut_cpcp_order_two_conj.
        -- Helper: cyclicHom evaluated at g₂ gives the underlying element.
        have hval_g₂ : ((Multiplicative.toAdd g₂).val : ℤ) = 1 := by
          change ((1 : ZMod 2).val : ℤ) = 1
          rw [ZMod.val_one_eq_one_mod]; norm_num
        have h_r1_g₂ : canonicalC2OnCpCpAction_r1 p g₂ = cpcpInvSecond p := by
          show (cyclicHom 2 (cpcpInvSecond p) (cpcpInvSecond_sq p)) g₂ = cpcpInvSecond p
          rw [cyclicHom_apply_eq_zpow, hval_g₂]; exact zpow_one _
        have h_r2_g₂ : canonicalC2OnCpCpAction_r2 p g₂ = cpcpInvBoth p := by
          show (cyclicHom 2 (cpcpInvBoth p) (cpcpInvBoth_sq p)) g₂ = cpcpInvBoth p
          rw [cyclicHom_apply_eq_zpow, hval_g₂]; exact zpow_one _
        rcases mulAut_cpcp_order_two_conj hp_ne_2 σ hσ_order with h_conj1 | h_conj2
        · -- σ is conjugate to cpcpInvSecond p, hence φ_inter ≅ canonicalC2OnCpCpAction_r1 p
          obtain ⟨cu, hcu⟩ := h_conj1
          -- hcu : SemiconjBy (↑cu) (cpcpInvSecond p) σ, i.e. ↑cu * cpcpInvSecond p = σ * ↑cu.
          let c : MulAut (CyclicGroup p × CyclicGroup p) := (cu : MulAut _)
          have hc_eq : σ = c * cpcpInvSecond p * c⁻¹ := by
            have h1 : c * cpcpInvSecond p = σ * c := hcu
            have h2 : c * cpcpInvSecond p * c⁻¹ = σ * c * c⁻¹ := by rw [h1]
            rw [h2, mul_inv_cancel_right]
          let conj_hom : CyclicGroup 2 →* MulAut (CyclicGroup p × CyclicGroup p) :=
            { toFun := fun x => c * canonicalC2OnCpCpAction_r1 p x * c⁻¹
              map_one' := by simp
              map_mul' := fun a b => by
                simp only [map_mul]; group }
          have h_eq_on_g₂ : φ_inter g₂ = conj_hom g₂ := by
            show σ = c * canonicalC2OnCpCpAction_r1 p g₂ * c⁻¹
            rw [h_r1_g₂]; exact hc_eq
          have h_eq : φ_inter = conj_hom :=
            monoidHom_eq_of_generator_eq hg₂_gen h_eq_on_g₂
          have h_action_eq : ∀ x : CyclicGroup 2,
              φ_inter x = c * canonicalC2OnCpCpAction_r1 p x * c⁻¹ :=
            fun x => congr_fun (congr_arg DFunLike.coe h_eq) x
          obtain ⟨e_iso⟩ := semidirectProduct_iso_of_conjugate_action
            (f_1 := canonicalC2OnCpCpAction_r1 p)
            (f_2 := φ_inter) c 1
            (fun x => by simpa using h_action_eq x)
          have : G ≃* SemidirectProduct (CyclicGroup p × CyclicGroup p) (CyclicGroup 2)
                       (canonicalC2OnCpCpAction_r1 p) :=
            h_iso_g_n_k.symm.trans (h_congr.trans e_iso.symm)
          tauto
        · -- σ is conjugate to cpcpInvBoth p, hence φ_inter ≅ canonicalC2OnCpCpAction_r2 p
          obtain ⟨cu, hcu⟩ := h_conj2
          let c : MulAut (CyclicGroup p × CyclicGroup p) := (cu : MulAut _)
          have hc_eq : σ = c * cpcpInvBoth p * c⁻¹ := by
            have h1 : c * cpcpInvBoth p = σ * c := hcu
            have h2 : c * cpcpInvBoth p * c⁻¹ = σ * c * c⁻¹ := by rw [h1]
            rw [h2, mul_inv_cancel_right]
          let conj_hom : CyclicGroup 2 →* MulAut (CyclicGroup p × CyclicGroup p) :=
            { toFun := fun x => c * canonicalC2OnCpCpAction_r2 p x * c⁻¹
              map_one' := by simp
              map_mul' := fun a b => by
                simp only [map_mul]; group }
          have h_eq_on_g₂ : φ_inter g₂ = conj_hom g₂ := by
            show σ = c * canonicalC2OnCpCpAction_r2 p g₂ * c⁻¹
            rw [h_r2_g₂]; exact hc_eq
          have h_eq : φ_inter = conj_hom :=
            monoidHom_eq_of_generator_eq hg₂_gen h_eq_on_g₂
          have h_action_eq : ∀ x : CyclicGroup 2,
              φ_inter x = c * canonicalC2OnCpCpAction_r2 p x * c⁻¹ :=
            fun x => congr_fun (congr_arg DFunLike.coe h_eq) x
          obtain ⟨e_iso⟩ := semidirectProduct_iso_of_conjugate_action
            (f_1 := canonicalC2OnCpCpAction_r2 p)
            (f_2 := φ_inter) c 1
            (fun x => by simpa using h_action_eq x)
          have : G ≃* SemidirectProduct (CyclicGroup p × CyclicGroup p) (CyclicGroup 2)
                       (canonicalC2OnCpCpAction_r2 p) :=
            h_iso_g_n_k.symm.trans (h_congr.trans e_iso.symm)
          tauto
  · -- n_2 = 1: Sylow 2-subgroup Q (order 2) is normal, complement K of order p²
    let Q : Sylow 2 G := default
    haveI : Subsingleton (Sylow 2 G) := (Nat.card_eq_one_iff_unique.mp h_n2_1).1
    have h_Q_card : Nat.card ↥(Q : Subgroup G) = 2 := by
      simpa using sylow_card_eq (Ne.symm hpne2) h_2_p2_card Q
    have h_Q_idx_p2 : ∀ Q : Sylow 2 G, (↑Q : Subgroup G).index = p ^ 2 := fun Q => by
      simpa using sylow_index_eq (Ne.symm hpne2) h_2_p2_card Q
    obtain ⟨K, hK⟩ := Subgroup.exists_right_complement'_of_coprime
      (N := (↑Q : Subgroup G)) (by
      rw [h_Q_card, h_Q_idx_p2]
      exact ((by norm_num : (2 : ℕ).Prime).coprime_of_ne h_p_prime.out
        (by omega : (2 : ℕ) ≠ p)).pow_right 2)
    have h_iso_g_q_k := SemidirectProduct.mulEquivSubgroup hK
    let φ : ↥K →* MulAut ↥(↑Q : Subgroup G) :=
      (↑Q : Subgroup G).normalizerMonoidHom.comp
        (Subgroup.inclusion (by simp [Subgroup.normalizer_eq_top]))
    have hK_card : Nat.card ↥K = p ^ 2 := by
      have h1 : Nat.card G = Nat.card ↥(↑Q : Subgroup G) * Nat.card ↥K := by
        have heq := Nat.card_congr h_iso_g_q_k.toEquiv
        rw [SemidirectProduct.card] at heq; exact heq.symm
      rw [h_Q_card, h] at h1
      exact (Nat.eq_of_mul_eq_mul_right (by norm_num : 0 < 2) (by linarith))
    have eQ : ↥(↑Q : Subgroup G) ≃* CyclicGroup 2 :=
      Classical.choice (prime_classification_of_group (n := 2) h_Q_card)
    -- Aut(C_2) is trivial since |Aut(C_2)| = 1
    have h_aut_card : Nat.card (MulAut ↥(↑Q : Subgroup G)) = 1 := by
      have h_iso_aut : MulAut ↥(↑Q : Subgroup G) ≃* MulAut (CyclicGroup 2) :=
        MulAut.congr eQ
      have h_aut_c2 : Nat.card (MulAut (CyclicGroup 2)) = 1 := by
        have := card_mulAut_cyclicGroup_prime (q := 2)
        simpa using this
      exact (Nat.card_congr h_iso_aut.toEquiv).trans h_aut_c2
    -- φ trivial since codomain has cardinality 1
    have h_phi_triv : φ = 1 := eq_one_of_coprime_card (by
      rw [hK_card, h_aut_card]; simp)
    have h_2p2cop : Nat.Coprime 2 (p ^ 2) := h2cop.pow_right 2
    have h_p22cop : Nat.Coprime (p ^ 2) 2 := h_2p2cop.symm
    rcases (p_squared_classification (p := p) hK_card) with h_K_Cp2 | h_K_CpCp
    · -- K ≅ C_{p²}: G ≅ C_2 × C_{p²} ≅ C_{2p²}
      let eK := h_K_Cp2.some
      have : G ≃* CyclicGroup (2 * p ^ 2) := h_iso_g_q_k.symm.trans
        ((SemidirectProduct.mulEquivOfTrivialAction h_phi_triv).trans
          ((eQ.prodCongr eK).trans (CyclicGroup.prodMulEquiv h_2p2cop)))
      tauto
    · -- K ≅ C_p × C_p: G ≅ C_2 × (C_p × C_p) ≅ C_p × C_p × C_2
      let eK := h_K_CpCp.some
      have : G ≃* CyclicGroup p × CyclicGroup p × CyclicGroup 2 := h_iso_g_q_k.symm.trans
        ((SemidirectProduct.mulEquivOfTrivialAction h_phi_triv).trans
          ((eQ.prodCongr eK).trans (MulEquiv.prodComm.trans MulEquiv.prodAssoc)))
      tauto
