import Mathlib
import «M2rGroup7».SmallGroupsLibrary

set_option maxHeartbeats 800000

/-!
# Case C: Both generators have order 4 → Q₈

We prove that a non-abelian group G of order 8 with two non-commuting
elements of order 4 is isomorphic to QuaternionGroup 2.
-/

variable {G : Type*} [Group G]

/-
The subgroup ⟨a⟩ is normal in G when orderOf a = 4 and |G| = 8 (index 2).
-/
lemma caseC_zpowers_normal {a : G} (ha : orderOf a = 4) (hcard : Nat.card G = 8) :
    (Subgroup.zpowers a).Normal := by
  rcases finite_or_infinite G with h | h <;> have := Subgroup.card_mul_index ( Subgroup.zpowers a ) <;> simp_all +decide [ Nat.card_eq_fintype_card ];
  exact Subgroup.normal_of_index_eq_two ( by omega )

/-
Key conjugation relation: b * a * b⁻¹ = a⁻¹ when both have order 4 and don't commute
-/
lemma caseC_conj_inv {a b : G} (ha : orderOf a = 4) (hb : orderOf b = 4)
    (hab : a * b ≠ b * a) (hcard : Nat.card G = 8) :
    b * a * b⁻¹ = a⁻¹ := by
  -- Since ⟨a⟩ is normal, b * a * b⁻¹ ∈ ⟨a⟩. Thus b * a * b⁻¹ = a^k for some integer k.
  obtain ⟨k, hk⟩ : ∃ k : ℤ, b * a * b⁻¹ = a^k := by
    have h_normal : Subgroup.Normal (Subgroup.zpowers a) := by
      apply caseC_zpowers_normal ha hcard;
    exact Subgroup.mem_zpowers_iff.mp ( h_normal.conj_mem _ ( Subgroup.mem_zpowers a ) b ) |> fun ⟨ k, hk ⟩ => ⟨ k, hk.symm ⟩;
  -- Since conjugation preserves order, orderOf(a^k) = 4. The elements of ⟨a⟩ are {1, a, a², a³} with orders {1, 4, 2, 4}. So a^k has order 4, meaning a^k = a or a^k = a³ = a⁻¹.
  have h_order : orderOf (a^k) = 4 := by
    rw [ ← hk, orderOf_eq_iff ] at * <;> aesop
  have h_cases : a^k = a ∨ a^k = a^3 := by
    -- Since $a$ has order 4, we know that $a^k$ can only be $1$, $a$, $a^2$, or $a^3$.
    have h_cases : ∃ m : ℕ, m < 4 ∧ a^k = a^m := by
      use Int.toNat ( k % 4 );
      rw [ ← zpow_mod_orderOf ] ; simp +decide [ ha ];
      exact ⟨ Int.emod_lt_of_pos _ ( by decide ), by rw [ ← zpow_natCast, Int.toNat_of_nonneg ( Int.emod_nonneg _ ( by decide ) ) ] ⟩;
    rcases h_cases with ⟨ m, hm, hm' ⟩ ; interval_cases m <;> simp_all +decide ;
    simp_all +decide [ orderOf_pow' ];
  cases' h_cases with h h <;> simp_all +decide [ pow_succ', mul_assoc ];
  · simp_all +decide [ ← mul_assoc ];
    simp_all +decide [ mul_inv_eq_iff_eq_mul ];
  · simp_all +decide [ mul_assoc, eq_inv_iff_mul_eq_one, orderOf_eq_iff ];
    simp_all +decide [ mul_assoc, pow_succ ]

/-
b² = a² when both have order 4, |G| = 8, and they don't commute
-/
lemma caseC_sq_eq {a b : G} (ha : orderOf a = 4) (hb : orderOf b = 4)
    (hab : a * b ≠ b * a) (hcard : Nat.card G = 8) :
    b ^ 2 = a ^ 2 := by
  -- Since $a^2$ commutes with $b$, we have $b * (a^2 * b⁻¹) = a^2$.
  have h_comm : b * (a^2 * b⁻¹) = a^2 := by
    have := caseC_conj_inv ha hb hab hcard;
    simp_all +decide [ mul_inv_eq_iff_eq_mul, sq ];
    simp +decide [ ← mul_assoc, this ];
    simp +decide [ mul_assoc, this ];
    simp +decide [ ← mul_assoc, ← pow_two, ha ▸ pow_orderOf_eq_one a ];
    rw [ inv_eq_of_mul_eq_one_right ] ; simp +decide [ ← pow_add, ha ▸ pow_orderOf_eq_one a ];
  -- Since $b^2$ is in the subgroup generated by $a$, we have $b^2 = a^k$ for some $k$.
  obtain ⟨k, hk⟩ : ∃ k : ℕ, b^2 = a^k := by
    have h_b2_in_a : b^2 ∈ Subgroup.zpowers a := by
      -- Since $\langle a \rangle$ is a subgroup of $G$ with index 2, it is normal.
      have h_normal : Subgroup.Normal (Subgroup.zpowers a) := by
        exact?;
      have h_quotient : ∀ x : G ⧸ Subgroup.zpowers a, x^2 = 1 := by
        intro x
        have h_card : Nat.card (G ⧸ Subgroup.zpowers a) = 2 := by
          have := Subgroup.card_eq_card_quotient_mul_card_subgroup ( Subgroup.zpowers a );
          simp_all +decide [ Nat.card_eq_fintype_card, Fintype.card_zpowers ];
          linarith
        simp +decide [ ← h_card, pow_card_eq_one ];
      simpa [ ← QuotientGroup.eq_one_iff ] using h_quotient ( QuotientGroup.mk b );
    obtain ⟨ k, hk ⟩ := h_b2_in_a; use Int.toNat ( k % 4 ) ; simp_all +decide [ ← zpow_natCast, Int.emod_nonneg, Int.emod_lt_of_pos ] ;
    rw [ ← hk, ← Int.emod_add_mul_ediv k 4, zpow_add, zpow_mul ] ; norm_cast ; simp +decide [ pow_mul, ha.symm, pow_orderOf_eq_one ];
  -- Since $a$ has order 4, we know that $a^k = a^m$ if and only if $k \equiv m \pmod{4}$.
  have h_mod : k % 4 = 2 := by
    have h_mod : orderOf (a^k) = 2 := by
      rw [ ← hk, orderOf_pow' ] <;> simp +decide [ hb ];
    rw [ orderOf_pow' ] at h_mod <;> simp_all +decide;
    · rw [ ← Nat.mod_add_div k 4 ] at *; have := Nat.mod_lt k zero_lt_four; interval_cases k % 4 <;> simp_all +decide ;
    · aesop;
  rw [ hk, ← Nat.mod_add_div k 4, h_mod ] ; simp +decide [ pow_add, pow_mul, ha ] ;
  rw [ ← ha, pow_orderOf_eq_one, one_pow ]

/-
Conjugation by b sends a^k to a^(-k)
-/
lemma caseC_conj_pow {a b : G} (ha : orderOf a = 4) (hb : orderOf b = 4)
    (hab : a * b ≠ b * a) (hcard : Nat.card G = 8) (k : ℕ) :
    b * a ^ k * b⁻¹ = a⁻¹ ^ k := by
  convert ( caseC_conj_inv ha hb hab hcard ) ▸ ( show b * a ^ k * b⁻¹ = ( b * a * b⁻¹ ) ^ k from ?_ ) using 1;
  simp +decide [ mul_pow, ← mul_assoc ]

/-
g^(val(i+j)) = g^(val i) * g^(val j) when orderOf g = 4
-/
lemma caseC_pow_val_add (g : G) (hord : orderOf g = 4) (i j : ZMod (2 * 2)) :
    g ^ (i + j).val = g ^ i.val * g ^ j.val := by
  fin_cases i <;> fin_cases j <;> simp +decide [ pow_add, pow_mul, hord ];
  all_goals simp_all +decide [ pow_succ, ZMod ];
  all_goals simp_all +decide [ ZMod.val, pow_succ, mul_assoc, orderOf_eq_iff ] ;

/-
g^(val(j-i)) = (g⁻¹)^(val i) * g^(val j) when orderOf g = 4
-/
lemma caseC_pow_val_sub (g : G) (hord : orderOf g = 4) (i j : ZMod 4) :
    g ^ (j - i).val = (g⁻¹) ^ i.val * g ^ j.val := by
      -- Since $j - i = (j - i).val$, we can rewrite the exponentiation.
    have h_exp : g ^ j.val = (g ^ i.val) * (g ^ (j - i).val) := by
      convert caseC_pow_val_add g hord i ( j - i ) using 1;
      simp +decide;
    simp +decide [ h_exp, mul_assoc ]

/-
g^(val(2+j-i)) = g^2 * (g⁻¹)^(val i) * g^(val j) when orderOf g = 4
-/
lemma caseC_pow_val_xa_xa (g : G) (hord : orderOf g = 4) (i j : ZMod (2 * 2)) :
    g ^ ((2 : ZMod (2 * 2)) + j - i).val = g ^ 2 * (g⁻¹) ^ i.val * g ^ j.val := by
  convert caseC_pow_val_sub g hord i ( 2 + j ) using 1;
  have := caseC_pow_val_add g hord 2 j; simp_all +decide [ pow_add, pow_mul ] ;
  simp +decide [ ← mul_assoc, ← pow_add, ZMod.val ];
  group
  congr 1
  omega

/-- The function QuaternionGroup 2 → G -/
noncomputable def quatToG (a b : G) : QuaternionGroup 2 → G
  | QuaternionGroup.a i => a ^ i.val
  | QuaternionGroup.xa i => b * a ^ i.val

/-- quatToG sends 1 to 1 -/
lemma quatToG_one (a b : G) : quatToG a b 1 = 1 := by
  show quatToG a b (QuaternionGroup.a 0) = 1
  simp [quatToG]

/-
The map quatToG is a group homomorphism
-/
lemma quatToG_mul (a b : G) (ha : orderOf a = 4) (hb : orderOf b = 4)
    (hab : a * b ≠ b * a) (hcard : Nat.card G = 8)
    (x y : QuaternionGroup 2) :
    quatToG a b (x * y) = quatToG a b x * quatToG a b y := by
  induction x using QuaternionGroup.rec <;> induction y using QuaternionGroup.rec;
  · exact caseC_pow_val_add a ha _ _;
  · simp +decide [ quatToG ];
    rename_i i j;
    rw [ ← mul_assoc, caseC_pow_val_sub ];
    · have := caseC_conj_pow ha hb hab hcard i.val; simp_all +decide [ mul_assoc, pow_succ ] ;
      simp_all +decide [ mul_inv_eq_iff_eq_mul, ← mul_assoc ];
      simp_all +decide [ mul_assoc, eq_inv_mul_iff_mul_eq ];
    · exact ha;
  · -- By definition of quatToG, we have quatToG a b (QuaternionGroup.xa i * QuaternionGroup.a j) = b * a ^ i.val * a ^ j.val.
    simp [quatToG];
    simp +decide [ mul_assoc, ← pow_add, caseC_pow_val_add a ha ];
  · rename_i i j
    have h_conj : b * a ^ i.val * b * a ^ j.val = a ^ 2 * (a⁻¹) ^ i.val * a ^ j.val := by
      have h_conj : b * a ^ i.val * b = a⁻¹ ^ i.val * b ^ 2 := by
        have h_conj : b * a ^ i.val * b⁻¹ = a⁻¹ ^ i.val := by
          convert caseC_conj_pow ha hb hab hcard i.val using 1;
        simp +decide [ ← h_conj, sq, mul_assoc ];
      rw [ h_conj, caseC_sq_eq ha hb hab hcard ] ; group;
    convert h_conj.symm using 1;
    · convert caseC_pow_val_xa_xa a ha i j using 1;
    · unfold quatToG; simp +decide [ mul_assoc ] ;

/-- The MonoidHom from QuaternionGroup 2 to G -/
noncomputable def quatHomToG (a b : G) (ha : orderOf a = 4) (hb : orderOf b = 4)
    (hab : a * b ≠ b * a) (hcard : Nat.card G = 8) : QuaternionGroup 2 →* G where
  toFun := quatToG a b
  map_one' := quatToG_one a b
  map_mul' := quatToG_mul a b ha hb hab hcard

/-
The map is injective
-/
lemma quatToG_injective (a b : G) (ha : orderOf a = 4) (hb : orderOf b = 4)
    (hab : a * b ≠ b * a) (hcard : Nat.card G = 8) :
    Function.Injective (quatToG a b) := by
  -- To prove injectivity, we show that if quatHomToG a b x = 1, then x must be 1. We consider the cases where x is of the form a^i or xa^i.
  have h_cases : ∀ x : QuaternionGroup 2, quatToG a b x = 1 → x = 1 := by
    intro x hx; rcases x with ( x | x ) <;> simp_all +decide [ pow_succ' ] ;
    · fin_cases x <;> simp_all +decide [ pow_succ', quatToG ];
      · simp_all +decide [ ZMod.val ];
      · have := orderOf_dvd_iff_pow_eq_one.mpr hx; simp_all +decide ;
      · have := orderOf_dvd_iff_pow_eq_one.mpr hx; simp_all +decide ;
    · -- If $b * a^x = 1$, then $b = a^{-x}$, which implies $b \in \langle a \rangle$, contradicting $a * b \neq b * a$.
      have h_contra : b = a⁻¹ ^ x.val := by
        exact eq_inv_of_mul_eq_one_left hx ▸ by group;
      simp_all +decide [ mul_assoc, pow_succ ];
      exact False.elim ( hab ( by group ) );
  intro x y hxy;
  specialize h_cases ( x * y⁻¹ ) ; simp_all +decide [ mul_inv_eq_iff_eq_mul ] ;
  have := quatToG_mul a b ha hb hab hcard x y⁻¹; simp_all +decide [ mul_inv_eq_iff_eq_mul ] ;
  exact h_cases ( by rw [ ← quatToG_mul a b ha hb hab hcard, mul_inv_cancel, quatToG_one ] )

/-- Main theorem: G ≅ QuaternionGroup 2 -/
theorem case_C_isom (a b : G) (ha : orderOf a = 4) (hb : orderOf b = 4)
    (hab : a * b ≠ b * a) (hcard : Nat.card G = 8) :
    Nonempty (G ≃* QuaternionGroup 2) := by
  have hinj := quatToG_injective a b ha hb hab hcard
  have hfin_G : Finite G := Nat.finite_of_card_ne_zero (by rw [hcard]; omega)
  have hcard_Q : Nat.card (QuaternionGroup 2) = 8 := by
    rw [Nat.card_eq_fintype_card]; decide
  have hsurj : Function.Surjective (quatToG a b) := by
    haveI : Fintype (QuaternionGroup 2) := Fintype.ofFinite _
    haveI : Fintype G := Fintype.ofFinite G
    have e : QuaternionGroup 2 ≃ G :=
      Fintype.equivOfCardEq (by rw [← Nat.card_eq_fintype_card, ← Nat.card_eq_fintype_card,
        hcard_Q, hcard])
    exact hinj.surjective_of_finite e
  exact ⟨(MulEquiv.ofBijective (quatHomToG a b ha hb hab hcard) ⟨hinj, hsurj⟩).symm⟩
